### ISSUE TITLE
Is it possible to use the module for 1d correlation only

### ISSUE THREAD

**Issue by fuy34** [ClementPinard/Pytorch-Correlation-extension#10]
Hi, thanks for the package!
Is it possible to use this module to perform 1D correlation? 
By saying 1d correlation, I mean to do correlation only along X direction, or Y direction, or certain customized direction (e.g. along epipolar line)  to save some computation. 
if not,  would you mind offer some hints to modify the code for that?

**Comment by ClementPinard** [comment]
The parameters are the same as convolutions. Namely, if you specify only a scalar for kernel size or patch size, you will get square values , but you can give two scalars to get non square kernel and patch.

Here you can specify a parch size of (1,n) to get a 1D correlation easily!

**Comment by fuy34** [comment]
It is cool! Thank you.
