### ISSUE TITLE
error installing on Mac

### ISSUE THREAD

**Issue by niujiaopeng** [ClementPinard/Pytorch-Correlation-extension#11]
Hi,
when I'm trying to install on Mac，here is the error:raise EnvironmentError('CUDA_HOME environment variable is not set).my pytorch version is 0.4.1，python is 3.6; because pytorch on Mac only support cpu, so I don't need set CUDA_HOME environment may be, any suggestion?

**Comment by ClementPinard** [comment]
You can try to pop the `.cu` file from this line : https://github.com/ClementPinard/Pytorch-Correlation-extension/blob/master/setup.py#L8

Can you stack the entire stacktrace ? Maybe there's an error when trying to import the `CUDAExtension` from the module `torch.utils.cpp_extension` . Inb that case, you may have to replace the `CUDAExtension` import to `CppExtension`. The code for both functions is here : https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L401
