### ISSUE TITLE
error: command 'D:\\Tool\\cuda11.3\\bin\\nvcc.exe' failed with exit code 1

### ISSUE THREAD

**Issue by corhrther** [ClementPinard/Pytorch-Correlation-extension#110]
python3.7
cuda11.3
gcc7.5
torch1.11
I installed it on windows and it failed:

D:\Tool\cuda11.3\bin\nvcc -c Correlation_Module\correlation_cuda_kernel.cu -o build\temp.win-amd64-cpython-37\Release\Correlation_Module\correlation_cuda_kernel.obj -ID:\Anaconda3\envs\mrc3.7_cuda11.5\lib\site-packages\torch\include -ID:\Anaconda3\envs\mrc3.7_cuda11.5\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\mrc3.7_cuda11.5\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\mrc3.7_cuda11.5\lib\site-packages\torch\include\THC -ID:\Tool\cuda11.3\include -ID:\Anaconda3\envs\mrc3.7_cuda11.5\include -ID:\Anaconda3\envs\mrc3.7_cuda11.5\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --use-local-env
error: command 'D:\\Tool\\cuda11.3\\bin\\nvcc.exe' failed with exit code 1

How can I solve it? Should I modify correlation_cuda_kernel.cu?

**Comment by ClementPinard** [comment]
Hi, there is no official support for windows, as I only use Linux.

I can try ot decipher the error message, but can't guanrantee anything. Can you print the full stacktrace ? looks like the actual error log is not in you snippet.

**Comment by corhrther** [comment]
I run this code alone not in 'python setup.py install' and it succeeds(:
D:\Tool\cuda11.3\bin\nvcc -c Correlation_Module\correlation_cuda_kernel.cu -o build\temp.win-amd64-cpython-37\Release\Correlation_Module\correlation_cuda_kernel.obj -ID:\Anaconda3\envs\mrc3.7_cuda11.5\lib\site-packages\torch\include -ID:\Anaconda3\envs\mrc3.7_cuda11.5\lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\envs\mrc3.7_cuda11.5\lib\site-packages\torch\include\TH -ID:\Anaconda3\envs\mrc3.7_cuda11.5\lib\site-packages\torch\include\THC -ID:\Tool\cuda11.3\include -ID:\Anaconda3\envs\mrc3.7_cuda11.5\include -ID:\Anaconda3\envs\mrc3.7_cuda11.5\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --use-local-env

I think I should try it on linux

**Comment by corhrther** [comment]
Hi @ClementPinard , when I install it on linux, I meet some errors, could you give me some suggestions?
**Another error:**

I install it on linux successfully:
```
(mrc3.7_cuda11.3) root@dev-shijue010-mrcenv-t9jw-pod-0:/private/workspace/Pytorch-Correlation-extension# python setup.py install
running install
/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/torch/utils/cpp_extension.py:387: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-cpython-37/spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/spatial_correlation_sampler
copying build/lib.linux-x86_64-cpython-37/spatial_correlation_sampler/__init__.py -> build/bdist.linux-x86_64/egg/spatial_correlation_sampler
copying build/lib.linux-x86_64-cpython-37/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/bdist.linux-x86_64/egg/spatial_correlation_sampler
byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler/spatial_correlation_sampler.py to spatial_correlation_sampler.cpython-37.pyc
creating stub loader for spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler_backend.py to spatial_correlation_sampler_backend.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.spatial_correlation_sampler_backend.cpython-37: module references __file__
creating 'dist/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg
creating /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg
Extracting spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg to /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages
Adding spatial-correlation-sampler 0.5.0 to easy-install.pth file

Installed /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg
Processing dependencies for spatial-correlation-sampler==0.5.0
Searching for numpy==1.21.5
Best match: numpy 1.21.5
Adding numpy 1.21.5 to easy-install.pth file
Installing f2py script to /private/workspace/mrc3.7_cuda11.3/bin
Installing f2py3 script to /private/workspace/mrc3.7_cuda11.3/bin
Installing f2py3.7 script to /private/workspace/mrc3.7_cuda11.3/bin

Using /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages
Searching for torch==1.11.0
Best match: torch 1.11.0
Adding torch 1.11.0 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /private/workspace/mrc3.7_cuda11.3/bin
Installing convert-onnx-to-caffe2 script to /private/workspace/mrc3.7_cuda11.3/bin
Installing torchrun script to /private/workspace/mrc3.7_cuda11.3/bin

Using /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages
Searching for typing-extensions==4.3.0
Best match: typing-extensions 4.3.0
Adding typing-extensions 4.3.0 to easy-install.pth file

Using /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages
Finished processing dependencies for spatial-correlation-sampler==0.5.0

```
 **but when I use it, it imports error:**

```
(mrc3.7_cuda11.3) root@dev-shijue010-mrcenv-t9jw-pod-0:/private/workspace/MRCNet-master# python evaluate_calib.py 
Traceback (most recent call last):
  File "evaluate_calib.py", line 31, in <module>
    from models.MRCNet import MRCNet
  File "/private/workspace/MRCNet-master/models/MRCNet.py", line 30, in <module>
    from spatial_correlation_sampler import SpatialCorrelationSampler
  File "/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, spatial_correlation_sample
  File "/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: Python version mismatch: module was compiled for Python 3.8, but the interpreter version is incompatible: 3.7.16 (default, Jan 17 2023, 22:20:44) 
[GCC 11.2.0].
(mrc3.7_cuda11.3) root@dev-shijue010-mrcenv-t9jw-pod-0:/private/workspace/MRCNet-master# python --version
Python 3.7.16
```

It imports that I used python3.8 to compiled the module, but python --version shows that the python version is 3.7. And if I use pip install spatial-correlation-sampler, when I use it, it imports another error:
```
(mrc3.7_cuda11.3) root@dev-shijue010-mrcenv-t9jw-pod-0:/private/workspace/MRCNet-master# python evaluate_calib.py 
Traceback (most recent call last):
  File "evaluate_calib.py", line 31, in <module>
    from models.MRCNet import MRCNet
  File "/private/workspace/MRCNet-master/models/MRCNet.py", line 30, in <module>
    from spatial_correlation_sampler import SpatialCorrelationSampler
  File "/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, spatial_correlation_sample
  File "/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE
```

**Comment by corhrther** [comment]
> Hi @ClementPinard , when I install it on linux, I meet some errors, could you give me some suggestions? **Another error:**
> 
> I install it on linux successfully:
> 
> ```
> (mrc3.7_cuda11.3) root@dev-shijue010-mrcenv-t9jw-pod-0:/private/workspace/Pytorch-Correlation-extension# python setup.py install
> running install
> /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>   setuptools.SetuptoolsDeprecationWarning,
> /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
>   EasyInstallDeprecationWarning,
> running bdist_egg
> running egg_info
> writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
> writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
> writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
> writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
> /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/torch/utils/cpp_extension.py:387: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>   warnings.warn(msg.format('we could not find ninja.'))
> reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
> adding license file 'LICENSE'
> writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> creating build/bdist.linux-x86_64/egg
> copying build/lib.linux-x86_64-cpython-37/spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/spatial_correlation_sampler
> copying build/lib.linux-x86_64-cpython-37/spatial_correlation_sampler/__init__.py -> build/bdist.linux-x86_64/egg/spatial_correlation_sampler
> copying build/lib.linux-x86_64-cpython-37/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/bdist.linux-x86_64/egg/spatial_correlation_sampler
> byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler/__init__.py to __init__.cpython-37.pyc
> byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler/spatial_correlation_sampler.py to spatial_correlation_sampler.cpython-37.pyc
> creating stub loader for spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so
> byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler_backend.py to spatial_correlation_sampler_backend.cpython-37.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
> zip_safe flag not set; analyzing archive contents...
> __pycache__.spatial_correlation_sampler_backend.cpython-37: module references __file__
> creating 'dist/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg
> creating /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg
> Extracting spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg to /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages
> Adding spatial-correlation-sampler 0.5.0 to easy-install.pth file
> 
> Installed /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg
> Processing dependencies for spatial-correlation-sampler==0.5.0
> Searching for numpy==1.21.5
> Best match: numpy 1.21.5
> Adding numpy 1.21.5 to easy-install.pth file
> Installing f2py script to /private/workspace/mrc3.7_cuda11.3/bin
> Installing f2py3 script to /private/workspace/mrc3.7_cuda11.3/bin
> Installing f2py3.7 script to /private/workspace/mrc3.7_cuda11.3/bin
> 
> Using /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages
> Searching for torch==1.11.0
> Best match: torch 1.11.0
> Adding torch 1.11.0 to easy-install.pth file
> Installing convert-caffe2-to-onnx script to /private/workspace/mrc3.7_cuda11.3/bin
> Installing convert-onnx-to-caffe2 script to /private/workspace/mrc3.7_cuda11.3/bin
> Installing torchrun script to /private/workspace/mrc3.7_cuda11.3/bin
> 
> Using /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages
> Searching for typing-extensions==4.3.0
> Best match: typing-extensions 4.3.0
> Adding typing-extensions 4.3.0 to easy-install.pth file
> 
> Using /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages
> Finished processing dependencies for spatial-correlation-sampler==0.5.0
> ```
> 
> **but when I use it, it imports error:**
> 
> ```
> (mrc3.7_cuda11.3) root@dev-shijue010-mrcenv-t9jw-pod-0:/private/workspace/MRCNet-master# python evaluate_calib.py 
> Traceback (most recent call last):
>   File "evaluate_calib.py", line 31, in <module>
>     from models.MRCNet import MRCNet
>   File "/private/workspace/MRCNet-master/models/MRCNet.py", line 30, in <module>
>     from spatial_correlation_sampler import SpatialCorrelationSampler
>   File "/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler/__init__.py", line 1, in <module>
>     from .spatial_correlation_sampler import SpatialCorrelationSampler, spatial_correlation_sample
>   File "/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler-0.5.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
>     import spatial_correlation_sampler_backend as correlation
> ImportError: Python version mismatch: module was compiled for Python 3.8, but the interpreter version is incompatible: 3.7.16 (default, Jan 17 2023, 22:20:44) 
> [GCC 11.2.0].
> (mrc3.7_cuda11.3) root@dev-shijue010-mrcenv-t9jw-pod-0:/private/workspace/MRCNet-master# python --version
> Python 3.7.16
> ```
> 
> It imports that I used python3.8 to compiled the module, but python --version shows that the python version is 3.7. And if I use pip install spatial-correlation-sampler, when I use it, it imports another error:
> 
> ```
> (mrc3.7_cuda11.3) root@dev-shijue010-mrcenv-t9jw-pod-0:/private/workspace/MRCNet-master# python evaluate_calib.py 
> Traceback (most recent call last):
>   File "evaluate_calib.py", line 31, in <module>
>     from models.MRCNet import MRCNet
>   File "/private/workspace/MRCNet-master/models/MRCNet.py", line 30, in <module>
>     from spatial_correlation_sampler import SpatialCorrelationSampler
>   File "/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler/__init__.py", line 1, in <module>
>     from .spatial_correlation_sampler import SpatialCorrelationSampler, spatial_correlation_sample
>   File "/private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
>     import spatial_correlation_sampler_backend as correlation
> ImportError: /private/workspace/mrc3.7_cuda11.3/lib/python3.7/site-packages/spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE
> ```

Finally I solve the first problem by re-git-clone the code and re-install it. It seems that the first problem occured because I use python3.8 to install it at first time and then it will use the cache to install.

**Comment by ClementPinard** [comment]
Glad you could solve it.

What you can do also when installing with pip is to run pip with the option `--no-build-isolation`

The thing is now pip uses isolated environnement for building. So it will create an environment from scratch to do the building, but then the torch version it will compiled against is not necessarily the one you have in your working environement.

This option makes it clear that you don't want the isolated environment. The build might be less reproducible but it will be linked against the right pytorch version (instead of the last one)

```pip install spatial-correlation-sampler --no-build-isolation```
