### ISSUE TITLE
undefined symbol: _ZTIN3c1021Auto

### ISSUE THREAD

**Issue by babahaji** [ClementPinard/Pytorch-Correlation-extension#15]
Hey, I got This error when I want to run:
import spatial_correlation_sampler_backend as correlation

"pip install spatial-correlation-sampler", passes. And then, when I import it in python,

from spatial_correlation_sampler import spatial_correlation_sample

lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

pytorch 1.0.1.post2
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
Cuda compilation tools, release 10.0, V10.0.130

**Comment by ClementPinard** [comment]
Fist guess is that you didn't import torch before. it's apparently a known problem (see [here](https://pytorch.org/cppdocs/notes/faq.html#undefined-symbol-errors-from-pytorch-aten) )

Does it work if you import torch before ?

**Comment by babahaji** [comment]
I imported torch before  spatial-correlation-sampler. I tried to run grad_check.py code in your repo, which imported firstly torch and later its extension  "spatial-correlation-sampler"; and got same error

**Comment by anuragranj** [comment]
I can't reproduce this error with gcc-7.3, pytorch1.0 (stable release), and cuda 10.0. What am I missing?

**Comment by babahaji** [comment]
I used same config:
---------
gcc -v 

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 

-----------
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
-------------
>>> import torch
>>> print(torch.__version__)
1.0.1.post2
--------
and here is error in importing:

import torch
from spatial_correlation_sampler import spatial_correlation_sample
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, SpatialCorrelationSamplerFunction, spatial_correlation_sample
  File "/usr/local/lib/python3.6/dist-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: /usr/local/lib/python3.6/dist-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

**Comment by anuragranj** [comment]
This is what I am doing, and no errors.

```bash
(pytorch1.0) aranjan@aranjan$ gcc --version
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(pytorch1.0) aranjan@aranjan$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
(pytorch1.0) aranjan@aranjan$ ipython
```

```python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch                                                                                  

In [2]: from spatial_correlation_sampler import SpatialCorrelationSampler                             

In [3]: torch.__version__                                                                             
Out[3]: '1.0.1.post2'

In [4]: from spatial_correlation_sampler import spatial_correlation_sample 

```

**Comment by ClementPinard** [comment]
Can you try to install from source and print the build output?

@anuragranj is your version up to date? I upgraded to 0.1.0 lately, to use the official torch cpp api instead of at and a little hack for multi dimensional indexing inside a kernel function. Anyway I also have gcc7 Cuda 10 with no problem with last version

**Comment by anuragranj** [comment]
@ClementPinard I also din't have any errors with building this. My torch version today's. It seems fine and compatible with this library. So, I haven't been able to reproduce @babahaji 's errors.

**Comment by babahaji** [comment]
> Can you try to install from source and print the build output?
> 
> @anuragranj is your version up to date? I upgraded to 0.1.0 lately, to use the official torch cpp api instead of at and a little hack for multi dimensional indexing inside a kernel function. Anyway I also have gcc7 Cuda 10 with no problem with last version



Pytorch-Correlation-extension# python setup.py install
running install
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/spatial_correlation_sampler
copying build/lib.linux-x86_64-3.6/spatial_correlation_sampler/__init__.py -> build/bdist.linux-x86_64/egg/spatial_correlation_sampler
copying build/lib.linux-x86_64-3.6/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/bdist.linux-x86_64/egg/spatial_correlation_sampler
copying build/lib.linux-x86_64-3.6/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler/spatial_correlation_sampler.py to spatial_correlation_sampler.cpython-36.pyc
creating stub loader for spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/spatial_correlation_sampler_backend.py to spatial_correlation_sampler_backend.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.spatial_correlation_sampler_backend.cpython-36: module references __file__
creating 'dist/spatial_correlation_sampler-0.1.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing spatial_correlation_sampler-0.1.0-py3.6-linux-x86_64.egg
removing '/usr/local/lib/python3.6/dist-packages/spatial_correlation_sampler-0.1.0-py3.6-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python3.6/dist-packages/spatial_correlation_sampler-0.1.0-py3.6-linux-x86_64.egg
Extracting spatial_correlation_sampler-0.1.0-py3.6-linux-x86_64.egg to /usr/local/lib/python3.6/dist-packages
spatial-correlation-sampler 0.1.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/spatial_correlation_sampler-0.1.0-py3.6-linux-x86_64.egg
Processing dependencies for spatial-correlation-sampler==0.1.0
Searching for numpy==1.16.3
Best match: numpy 1.16.3
Adding numpy 1.16.3 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.6 script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Searching for torch==1.0.1.post2
Best match: torch 1.0.1.post2
Adding torch 1.0.1.post2 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /usr/local/bin
Installing convert-onnx-to-caffe2 script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for spatial-correlation-sampler==0.1.0
____________

>>> import torch
>>> from spatial_correlation_sampler import SpatialCorrelationSampler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, SpatialCorrelationSamplerFunction, spatial_correlation_sample
  File "/usr/local/lib/python3.6/dist-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: /usr/local/lib/python3.6/dist-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

**Comment by ClementPinard** [comment]
It seems that the install script didn't build the module because it already found one, and just copied it instead.
Can you try to erase the folder build and rerun the install script?

**Comment by babahaji** [comment]
Solved. I build spatial_correlation_sampler with cuda 9 and forgot to rebuild after changing the cuda version. Thanks
