### ISSUE TITLE
Error in pip3 install spatial-correlation-sampler

### ISSUE THREAD

**Issue by zmlshiwo** [ClementPinard/Pytorch-Correlation-extension#16]
Hi, I try to install spatial_correlation_sampler with command,
`pip3 install spatial_correlation_sampler`
I get the follows errors,
`error:  command 'usr/local/cuda/bin/nvcc' failed with exit status 2.`
I use Ubuntu16.04, CUDA8.0, Python3.5, Pytorch1.0.1， GCC 5.4
Can you provide your version of CUDA, Python, Pytorch and GCC?
Thank you!

**Comment by anuragranj** [comment]
Check here:
https://github.com/ClementPinard/Pytorch-Correlation-extension#known-problems

**Comment by zmlshiwo** [comment]
@anuragranj Thank you. I will upgrade my cuda 8.0 to cuda 9.2.

**Comment by ClementPinard** [comment]
Alternatively, you can look at @charliememory comment in the mentionned [issue](https://github.com/ClementPinard/Pytorch-Correlation-extension/issues/1#issuecomment-478052992) if you can't change cuda version.

**Comment by xuleyoung** [comment]
Hi, I also meet this problem, gcc  version 4.9.4  python 3.7.3   pytorch 1.0.1.post2  CUDA 8.0  Ubuntu16.04,
Do I need to upgrade gcc ? 
Thank you~

**Comment by anuragranj** [comment]
I think it would just be much cleaner to use the newer cuda and gcc with pytorch1.0.

**Comment by Trainbow** [comment]
Hi, I try to install spatial_correlation_sampler with command,
pip3 install spatial_correlation_sampler
I get the follows errors,

Collecting spatial-correlation-sampler
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a6/d1/aa0a71739ce998f655286d966c0ad7aff765648431c054c34db7d58b811b/spatial_correlation_sampler-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-x71js0k2/spatial-correlation-sampler/setup.py", line 2, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-x71js0k2/spatial-correlation-sampler/

can you tell me how to solve it?
thank you

**Comment by ClementPinard** [comment]
Your python version fails to fin the torch module from pytorch.
You need to install pytorch before installing this module.
