### ISSUE TITLE
error python setup.py install

### ISSUE THREAD

**Issue by xuleyoung** [ClementPinard/Pytorch-Correlation-extension#17]
Hi, My torch version 1.0.1.
When I run python setup.py install, there are some outputs:

torch-version 1.0.1.post2
running install
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'spatial_correlation_sampler_backend' extension
gcc -pthread -B /media/data2/xly/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/media/data2/xly/anaconda3/include/python3.7m -c Correlation_Module/correlation.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /media/data2/xly/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/media/data2/xly/anaconda3/include/python3.7m -c Correlation_Module/correlation_sampler.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/media/data2/xly/anaconda3/include/python3.7m -c Correlation_Module/correlation_cuda_kernel.cu -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

/media/data2/xly/anaconda3/lib/python3.7/site-packages/torch/lib/include/pybind11/cast.h(1877): warning: nonstandard use of "auto" to both deduce the type from an initializer and to announce a trailing return type

1 error detected in the compilation of "/tmp/tmpxft_00004282_00000000-7_correlation_cuda_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2

**Comment by xuleyoung** [comment]
I'd like to know how to solve this error:
argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct".

**Comment by ClementPinard** [comment]
Not really sure what that means, but it appears to be linked to cuda files.
It appears you have a GPU with 2.0 cuda capabilities, and I think it is not compatible with pytorch, I guess you have a cpu-only version of pytorch ?

In that case, you can try to remove the cuda file from the setup.py so that you only compute the cpu version of this module. https://github.com/ClementPinard/Pytorch-Correlation-extension/blob/master/setup.py#L8

**Comment by xuleyoung** [comment]
Yes , I have 2 cuda files, root user cuda8 and  non-root user cuda9.  I have remove the cuda9 files.
and  remove cuda files from the setup.py, the problem solved.
Therefore， a GPU with 2.0 cuda capabilities， I’d like to know how to solve it better (I want to use cuda version)?
Thank you very much, it troubled me so long.

**Comment by xuleyoung** [comment]
when I  
`import torch
import torchvision
print(torch.cuda.is_available())`
The result is True.
I think cuda is available.
Thank you .

**Comment by ClementPinard** [comment]
Can run this snippet for example ? the `torch.cuda.isavailable()` is not enough to know if cuda is *usable*.

```python
a = torch.randn(10,10,device="cuda")
print(a+a)
```

Had the same probleme because I had cuda capabilities 5.0 instead of 5.2 and had to install pytorhc from source to get cuda.

The thing is I also happened to have a pc with a 2.0 GPU, and tried to install pytorch from source, and couldn't because cuda 9 is not copatible with gpu 2.0 anymore.

cuda8 might be compatible but cuda8 support was dropped by pytorch recently.

Best optioHad the same probleme because I had cuda capabilities 5.0 instead of 5.2 and had to install pytorhc from source to get cuda.

The thing is I also happened to have a pc with a 2.0 GPU, and tried to 

 * Only option : build pytorch 1.0.1 (and not 1.1.0 the version from which official support of cuda8 is dropped) from source with cuda8 and try to install this module on top (should still work with master, but not garanteed in the future)

 * Best option : abandon cuda on this gpu, try to replace it with a newer one (some cheap ones exist !), or run everything on CPU.

**Comment by xuleyoung** [comment]
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.randn(3,3,device="cuda")
>>> print(a+a)
tensor([[-1.6874, -1.9257,  0.2490],
        [-1.2273,  0.6355,  0.2286],
        [ 1.3380, -1.1968, -3.6699]], device='cuda:0')

some infos:
run code on server (public in lab ) not PC.
cuda 8+cudnn5.1 
I delete the cuda9.
Thank you.

**Comment by xuleyoung** [comment]
Hi,
I modify the *.cu file.
commet
 `#include <torch/extension.h>`
then add
`#include<torch/serialize/tensor.h>`
I don't why ,but it works.

**Comment by ClementPinard** [comment]
hi, thanks for sharing how you solved this !
So the `.cu` files don't need all that's inside `<torch/extension.h>` and something inside it makes it crash for some configurations.

Might be interesting to discuss it on official extension-cpp repo.

Colsing this issue but don't hesitate to reopen if e.g. the check scripts still don't work
