### ISSUE TITLE
sample code of opticalflow which use this Correlation 

### ISSUE THREAD

**Issue by griffintin** [ClementPinard/Pytorch-Correlation-extension#22]
@ClementPinard

Hi , thank you for your great work.
Is there any sample code which use the Correlation code to generate final optical flow?

**Comment by ClementPinard** [comment]
the correlation code in itself is used in FlowNetC inside the network.
you can see an example [here](https://github.com/ClementPinard/FlowNetPytorch/blob/master/models/util.py#L39)
