### ISSUE TITLE
Support mixed precision training with NVIDIA apex

### ISSUE THREAD

**Issue by ananyahjha93** [ClementPinard/Pytorch-Correlation-extension#25]
It would be great if the correlation cuda kernel supported half precision operations, which would enable us to use the library for mixed precision training with NVIDIA Apex. #

**Comment by ananyahjha93** [comment]
@ClementPinard Is there a particular reason why 'AT_DISPATCH_FLOATING_TYPES_AND_HALF' macro was changed to 'AT_DISPATCH_FLOATING_TYPES' in the commit 'correct backward algorithm'? Will simply changing it back enable support for half-precision? Does 'AT_DISPATCH_FLOATING_TYPES_AND_HALF' macro give wrong results during back-propagation?

**Comment by ClementPinard** [comment]
If I recall correctly there was not enough support of half tensors in ATen at the time, and the compilation would fail.

It might be better now and we can try! If compilation doesn't fail and tests still run smoothly  with doubles I'd advocate for this.

**Comment by ClementPinard** [comment]
I pushed changes to support mixed precision. Feel free to reopen the issue if there are some problems
