### ISSUE TITLE
How to install on Mac CPU

### ISSUE THREAD

**Issue by kkew3** [ClementPinard/Pytorch-Correlation-extension#26]
I found #11 and I had the same problem. Following suggestions there I made the following changes but with no luck:

- Removed `.cu` file from `sources` and changed `CUDAExtension` to `CppExtension` in `setup.py` (see attached `setup.py.txt`)
- I had `openmp` installed
- I built the wheel using `CXX=clang++ CC=clang python3 setup.py build`

The output is:

```
running build
running build_py
running build_ext
building 'spatial_correlation_sampler_backend' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -g -I$VIRTUAL_ENV/lib/python3.6/site-packages/torch/include -I$VIRTUAL_ENV/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I$VIRTUAL_ENV/lib/python3.6/site-packages/torch/include/TH -I$VIRTUAL_ENV/lib/python3.6/site-packages/torch/include/THC -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c Correlation_Module/correlation.cpp -o build/temp.macosx-10.9-x86_64-3.6/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
clang: error: unsupported option '-fopenmp'
error: command 'clang' failed with exit status 1
```

Thanks for help!

[setup.py.txt](https://github.com/ClementPinard/Pytorch-Correlation-extension/files/3545096/setup.py.txt)

**Comment by ClementPinard** [comment]
Hello,

this error does not seem related to this project but rather how to link openmp to a compiler in mac.
I found this issue, that you may find of interest : https://github.com/microsoft/LightGBM/issues/3

My first guess would be to try to change the setup.py at line 26 so that the `extra_compile_arg['cxx'] is `-openmp` rather than `-fopenmp` .

**Comment by kkew3** [comment]
Thanks for your reply. I changed `-fopenmp` to `-openmp`. Now there are  two more errors:

```
clang: error: no such file or directory: 'build/temp.macosx-10.9-x86_64-3.6/Correlation_Module/correlation.o'
clang: error: no such file or directory: 'build/temp.macosx-10.9-x86_64-3.6/Correlation_Module/correlation_sampler.o'
error: command 'clang++' failed with exit status 1
```

I found the two underlying `cpp` files under `Correlation_Module`. How should I get them compiled?

Thanks!

**Comment by ClementPinard** [comment]
seems like some interferences with you previous attempt at building. I'd say completely remove the build folder and and start over.

**Comment by kkew3** [comment]
Thanks for your reply. No it reoccurs even after rebuilding. Here's the whole stdout and stderr (attached build.out.txt). Thanks!

[build.out.txt](https://github.com/ClementPinard/Pytorch-Correlation-extension/files/3551006/build.out.txt)

**Comment by kkew3** [comment]
I solved the issue by changing back `-openmp` to `-fopenmp` and installed `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` (as per [this answer](https://stackoverflow.com/a/55588705/7881370)).

However, when I run `python check.py`, it gives another error:

```
Traceback (most recent call last):
  File "check.py", line 8, in <module>
    from spatial_correlation_sampler import SpatialCorrelationSampler
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/spatial_correlation_sampler-0.1.0-py3.6-macosx-10.9-x86_64.egg/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, SpatialCorrelationSamplerFunction, spatial_correlation_sample
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/spatial_correlation_sampler-0.1.0-py3.6-macosx-10.9-x86_64.egg/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: dlopen($VIRTUAL_ENV/lib/python3.6/site-packages/spatial_correlation_sampler-0.1.0-py3.6-macosx-10.9-x86_64.egg/spatial_correlation_sampler_backend.cpython-36m-darwin.so, 2): Symbol not found: __Z24correlation_cuda_forwardN2at6TensorES0_iiiiiiiiii
  Referenced from: $VIRTUAL_ENV/lib/python3.6/site-packages/spatial_correlation_sampler-0.1.0-py3.6-macosx-10.9-x86_64.egg/spatial_correlation_sampler_backend.cpython-36m-darwin.so
  Expected in: flat namespace
 in $VIRTUAL_ENV/lib/python3.6/site-packages/spatial_correlation_sampler-0.1.0-py3.6-macosx-10.9-x86_64.egg/spatial_correlation_sampler_backend.cpython-36m-darwin.so
```

It seems that somehow the cpp file still needs certain cuda component. How to solve it? Thanks for any suggestions!

**Comment by ClementPinard** [comment]
I just pushed changes, you can get the last version (tagged 0.2.0) and try to install with `setup_cpu.py` instead of `setup.py`

**Comment by kkew3** [comment]
Thank you so much!
