### ISSUE TITLE
Can I use pytorch==1.1 to install?

### ISSUE THREAD

**Issue by CXMANDTXW** [ClementPinard/Pytorch-Correlation-extension#27]
Hello,because of my cuda driver is not suit for pytorch1.2, and I can not update the service cuda driver version. So, if I use pytorch1.1, shall I modify some code?
I have test 1.1 version, and there is some unkown error.

**Comment by ClementPinard** [comment]
what error do you have ?

It might not compile due to small API changes in torch cpp, but if it compiles I'm pretty confident that it will run fine.

**Comment by CXMANDTXW** [comment]
thank you for your response, this is my error outputs :
running install
running bdist_egg
running egg_info
creating Correlation_Module/spatial_correlation_sampler.egg-info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/spatial_correlation_sampler
copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.7/spatial_correlation_sampler
copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.7/spatial_correlation_sampler
running build_ext
building 'spatial_correlation_sampler_backend' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/Correlation_Module
gcc -pthread -B /home/cxm/anaconda3/envs/horovod_flo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/cxm/anaconda3/envs/horovod_flo/lib/python3.7/site-packages/torch/include -I/home/cxm/anaconda3/envs/horovod_flo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cxm/anaconda3/envs/horovod_flo/lib/python3.7/site-packages/torch/include/TH -I/home/cxm/anaconda3/envs/horovod_flo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cxm/anaconda3/envs/horovod_flo/include/python3.7m -c Correlation_Module/correlation.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/cxm/anaconda3/envs/horovod_flo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/cxm/anaconda3/envs/horovod_flo/lib/python3.7/site-packages/torch/include -I/home/cxm/anaconda3/envs/horovod_flo/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cxm/anaconda3/envs/horovod_flo/lib/python3.7/site-packages/torch/include/TH -I/home/cxm/anaconda3/envs/horovod_flo/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cxm/anaconda3/envs/horovod_flo/include/python3.7m -c Correlation_Module/correlation_sampler.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Correlation_Module/correlation_sampler.cpp: In function ‘at::Tensor correlation_sample_forward(at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
Correlation_Module/correlation_sampler.cpp:29:83: error: ‘TORCH_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x, " must be a CUDA tensor")
                                                                                   ^
Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^
Correlation_Module/correlation_sampler.cpp:63:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(input1);
     ^
Correlation_Module/correlation_sampler.cpp: In function ‘std::vector<at::Tensor> correlation_sample_backward(at::Tensor, at::Tensor, at::Tensor, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t)’:
Correlation_Module/correlation_sampler.cpp:29:83: error: ‘TORCH_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x, " must be a CUDA tensor")
                                                                                   ^
Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^
Correlation_Module/correlation_sampler.cpp:89:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(input1);
     ^
error: command 'gcc' failed with exit status 1

**Comment by CXMANDTXW** [comment]
the error seems is 
(Correlation_Module/correlation_sampler.cpp:29:83: error: ‘TORCH_CHECK’ was not declared in this scope)

**Comment by ClementPinard** [comment]
Ok so before torch1.2, the function `AT_CHECK` was used. With the last version however, it has been replaced by `TORCH_CHECK` in order to get rid of all ATen references altogether.

So you might want to change all the `TORCH_CHECK`to `AT_CHECK` to make it compile. There should only be two, in the file [correlation_cuda_kernel.cu](https://github.com/ClementPinard/Pytorch-Correlation-extension/blob/master/Correlation_Module/correlation_cuda_kernel.cu)

**Comment by CXMANDTXW** [comment]
Great answer！Thank you very much.
A minor difference is TORCH_CHECK is in the file correlation_sampler.cpp :)
Unfortunately，when I run 'python benchmark.py cuda',。
error： ' Segmentation fault (core dumped)'  appeared. 
Can you please give me some advice?
pytorch 1.1,cuda 9.0

**Comment by CXMANDTXW** [comment]
There is no other message, only one line:
Segmentation fault (core dumped)

**Comment by ClementPinard** [comment]
What about with cpu ? What python version are you using ?
Can you try to build and use the official pytorch extension-cpp ?
https://github.com/pytorch/extension-cpp

**Comment by CXMANDTXW** [comment]
Sir, I am very sorry to bother you again.When I try 'python setup.py install', I meet this error:
/home/cxm/anaconda3/envs/test/compiler_compat/ld: cannot find -lm
I really don't why.This is very strange because I have not changed anything.

**Comment by CXMANDTXW** [comment]
In the case of cpu is also the same error.
Even in the official pytorch extension-cpp, the situation is exactly the same.
benchmark.py   grad_check.py   check.py three file will cause segmentation fault both in cpu and gpu.
But except that, install is fine.

anaconda3: pytorch 1.2 cuda10.0 cuda driver:386.(cuda driver version is not suit for cuda version)

when I turn to pytorch 1.1 cuda 9.0.(cuda driver version is suit for cuda version)
I didn't change TORCH_CHECK to AT_CHECK，but there is no previous error appears. It's very strange.
However, this situation has produced a new error:
Traceback (most recent call last):
  File "benchmark.py", line 8, in <module>
    from spatial_correlation_sampler import SpatialCorrelationSampler
  File "/home/cxm/anaconda3/envs/test/lib/python3.7/site-packages/spatial_correlation_sampler-0.2.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, spatial_correlation_sample
  File "/home/cxm/anaconda3/envs/test/lib/python3.7/site-packages/spatial_correlation_sampler-0.2.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: /home/cxm/anaconda3/envs/test/lib/python3.7/site-packages/spatial_correlation_sampler-0.2.0-py3.7-linux-x86_64.egg/spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

Both in cpu and gpu. It seems a compile problem.

**Comment by ClementPinard** [comment]
386 driver is way too low for cuda 10.0

you should try to remove the `build`directory to try to rebuild with the right cuda version.

**Comment by CXMANDTXW** [comment]
Hi, I I have spent one day to update my cuda ,Nvidia drive,and gcc version.
There are no problems now.
Thank you for your patience. Best wishes for you!

**Comment by gongbudaizhe** [comment]
I managed to make it work with CUDA 9.0, Driver 384.81 and PyTorch 1.1. 

1. Change the TORCH_CHECK in correlation_sampler.cpp to AT_CHECK
2. GCC 5.3 is used for compilation. Older versions may cause the segmentation fault.
