### ISSUE TITLE
How can I use this correlation repo to replace nvidia's

### ISSUE THREAD

**Issue by CXMANDTXW** [ClementPinard/Pytorch-Correlation-extension#28]
In Nvidia correlation file , I use Correlation(pad_size=4, kernel_size=1, max_displacement=4, stride1=1, stride2=1, corr_multiply=1)
So,I use correlation_sampler = SpatialCorrelationSampler( kernel_size=1,patch_size=4,stride=1,padding=0,dilation_patch=1)
Given input size torch.Size([8, 64, 7, 6]),output shape of your correlation_sampler is torch.Size([8, 4, 4, 7, 6]), while NVIDIA's implementation is torch.Size([8, 81, 7, 6]).
Thus, the convert code is:
b, ph, pw, h, w = output.size()
Nvidia_shape = output.view(b, (ph+pw+1)^2, h, w)
Is my approach correct?

**Comment by CXMANDTXW** [comment]
4*4 not equal 81, can not work. Can you give me some advice, thank you very much.

**Comment by ClementPinard** [comment]
Max displacement is in both directions, so the equivalent patch_size is 2*max_displacement+1 which is now 9

**Comment by CXMANDTXW** [comment]
Thanks, it works well now!
