### ISSUE TITLE
GCC error

### ISSUE THREAD

**Issue by superkevingit** [ClementPinard/Pytorch-Correlation-extension#29]
Thanks for the work, but I still have some troubles to compile the module. Following is my environment settings:

```
>> python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.1.0
```

```
>> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```

```
>> gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
>> g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

And I got these errors:
`>> python setup.py install`

running install
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'spatial_correlation_sampler_backend' extension
gcc -pthread -B /home/cvpr/anaconda3/envs/pwcnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/cvpr/anaconda3/envs/pwcnet/lib/python3.7/site-packages/torch/include -I/home/cvpr/anaconda3/envs/pwcnet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cvpr/anaconda3/envs/pwcnet/lib/python3.7/site-packages/torch/include/TH -I/home/cvpr/anaconda3/envs/pwcnet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cvpr/anaconda3/envs/pwcnet/include/python3.7m -c Correlation_Module/correlation.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/cvpr/anaconda3/envs/pwcnet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/cvpr/anaconda3/envs/pwcnet/lib/python3.7/site-packages/torch/include -I/home/cvpr/anaconda3/envs/pwcnet/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cvpr/anaconda3/envs/pwcnet/lib/python3.7/site-packages/torch/include/TH -I/home/cvpr/anaconda3/envs/pwcnet/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/cvpr/anaconda3/envs/pwcnet/include/python3.7m -c Correlation_Module/correlation_sampler.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
Correlation_Module/correlation_sampler.cpp: In function ‘at::Tensor correlation_sample_forward(at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
Correlation_Module/correlation_sampler.cpp:29:23: error: ‘TORCH_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x, " must be a CUDA tensor")
                       ^
Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
Correlation_Module/correlation_sampler.cpp:63:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(input1);
     ^~~~~~~~~~~
Correlation_Module/correlation_sampler.cpp:29:23: note: suggested alternative: ‘AT_CHECK’
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x, " must be a CUDA tensor")
                       ^
Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
Correlation_Module/correlation_sampler.cpp:63:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(input1);
     ^~~~~~~~~~~
Correlation_Module/correlation_sampler.cpp: In function ‘std::vector<at::Tensor> correlation_sample_backward(at::Tensor, at::Tensor, at::Tensor, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t)’:
Correlation_Module/correlation_sampler.cpp:29:23: error: ‘TORCH_CHECK’ was not declared in this scope
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x, " must be a CUDA tensor")
                       ^
Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
Correlation_Module/correlation_sampler.cpp:89:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(input1);
     ^~~~~~~~~~~
Correlation_Module/correlation_sampler.cpp:29:23: note: suggested alternative: ‘AT_CHECK’
 #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x, " must be a CUDA tensor")
                       ^
Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
 #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                        ^~~~~~~~~~
Correlation_Module/correlation_sampler.cpp:89:5: note: in expansion of macro ‘CHECK_INPUT’
     CHECK_INPUT(input1);
     ^~~~~~~~~~~
error: command 'gcc' failed with exit status 1

**Comment by superkevingit** [comment]
Switching to pytorch 1.2 and works. Refer to #27

**Comment by ClementPinard** [comment]
Yes sorry, the torch cpu API is changing pretty fast these days. This was due to dropping the "ATen" terminology altogether and using torch for everything for more clarity, I don't expect it to change too much after that.
