### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by shankyle** [ClementPinard/Pytorch-Correlation-extension#30]
Thanks for your valuable work! And I got this error when I find
`python setup_cpu.py install` on my MacBook pro without Cuda. Does it need Cuda installed when I just want to use it on CPU?(I have installed GCC)

**Comment by shankyle** [comment]
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
(base)
sky @ dankaiyudeMacBook-Pro in ~/Desktop/local_code/Pytorch-Correlation-extension on git:master x [19:33:45]
$ ls
Correlation_Module README.md          benchmark.py       check.py           requirements.txt   setup_cpu.py
LICENSE            __pycache__        build              grad_check.py      setup.py
(base)
 sky @ dankaiyudeMacBook-Pro in ~/Desktop/local_code/Pytorch-Correlation-extension on git:master x [19:34:12]
$ source activate mmlab
(mmlab)
 sky @ dankaiyudeMacBook-Pro in ~/Desktop/local_code/Pytorch-Correlation-extension on git:master x [19:34:23]
$ python setup_cpu.py
usage: setup_cpu.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup_cpu.py --help [cmd1 cmd2 ...]
   or: setup_cpu.py --help-commands
   or: setup_cpu.py cmd --help

error: no commands supplied
(mmlab)
sky @ dankaiyudeMacBook-Pro in ~/Desktop/local_code/Pytorch-Correlation-extension on git:master x [19:34:33] C:1
$ python setup_cpu.py install
running install
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py:166: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++) is not compatible with the compiler Pytorch was
built with for this platform, which is clang++ on darwin. Please
use clang++ to to compile your extension. Alternatively, you may
compile PyTorch from source using g++, and then you can also use
g++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
building 'spatial_correlation_sampler_backend' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sky/anaconda3/envs/mmlab/include -arch x86_64 -I/Users/sky/anaconda3/envs/mmlab/include -arch x86_64 -I/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include -I/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/TH -I/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/THC -I/Users/sky/anaconda3/envs/mmlab/include/python3.7m -c Correlation_Module/correlation.cpp -o build/temp.macosx-10.7-x86_64-3.7/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
clang: error: unsupported option '-fopenmp'
error: command 'gcc' failed with exit status 1

**Comment by ClementPinard** [comment]
Hello,

see issue #26 if it solves your problem.

**Comment by shankyle** [comment]
**When I tried the GPU version on cuda10 gcc5.4 I got the same command error as follows:**

```
(mmlab) shankaiyu@lthpc:~$ pip install spatial-correlation-sampler
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting spatial-correlation-sampler
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/69/62/96bda9bf47f2a2ea978ec86a2e0ac3631036e6650d02ee81ba769d8d5dae/spatial_correlation_sampler-0.2.1.tar.gz
Requirement already satisfied: torch>=1.1 in ./anaconda3/envs/mmlab/lib/python3.7/site-packages (from spatial-correlation-sampler) (1.1.0)
Requirement already satisfied: numpy in ./anaconda3/envs/mmlab/lib/python3.7/site-packages (from spatial-correlation-sampler) (1.16.4)
Building wheels for collected packages: spatial-correlation-sampler
  Building wheel for spatial-correlation-sampler (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/shankaiyu/anaconda3/envs/mmlab/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vz7ytcfu/spatial-correlation-sampler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vz7ytcfu/spatial-correlation-sampler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-okzhfi1j --python-tag cp37
       cwd: /tmp/pip-install-vz7ytcfu/spatial-correlation-sampler/
  Complete output (37 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.7/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.7/spatial_correlation_sampler
  running build_ext
  building 'spatial_correlation_sampler_backend' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/Correlation_Module
  gcc -pthread -B /home/shankaiyu/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shankaiyu/anaconda3/envs/mmlab/include/python3.7m -c Correlation_Module/correlation.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/shankaiyu/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shankaiyu/anaconda3/envs/mmlab/include/python3.7m -c Correlation_Module/correlation_sampler.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  Correlation_Module/correlation_sampler.cpp: In function ‘at::Tensor correlation_sample_forward(at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
  Correlation_Module/correlation_sampler.cpp:29:83: error: ‘TORCH_CHECK’ was not declared in this scope
   define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), x, " must be a CUDA tensor")
                                                                                     ^
  Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
   define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                          ^
  Correlation_Module/correlation_sampler.cpp:63:5: note: in expansion of macro ‘CHECK_INPUT’
       CHECK_INPUT(input1);
       ^
  Correlation_Module/correlation_sampler.cpp: In function ‘std::vector<at::Tensor> correlation_sample_backward(at::Tensor, at::Tensor, at::Tensor, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t)’:
  Correlation_Module/correlation_sampler.cpp:29:83: error: ‘TORCH_CHECK’ was not declared in this scope
  define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), x, " must be a CUDA tensor")
                                                                                     ^
  Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
   define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                          ^
  Correlation_Module/correlation_sampler.cpp:89:5: note: in expansion of macro ‘CHECK_INPUT’
       CHECK_INPUT(input1);
       ^
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for spatial-correlation-sampler
  Running setup.py clean for spatial-correlation-sampler
Failed to build spatial-correlation-sampler
Installing collected packages: spatial-correlation-sampler
  Running setup.py install for spatial-correlation-sampler ... error
    ERROR: Command errored out with exit status 1:
     command: /home/shankaiyu/anaconda3/envs/mmlab/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vz7ytcfu/spatial-correlation-sampler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vz7ytcfu/spatial-correlation-sampler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5f_7bmhn/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-vz7ytcfu/spatial-correlation-sampler/
    Complete output (37 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/spatial_correlation_sampler
    copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.7/spatial_correlation_sampler
    copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.7/spatial_correlation_sampler
    running build_ext
    building 'spatial_correlation_sampler_backend' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/Correlation_Module
    gcc -pthread -B /home/shankaiyu/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shankaiyu/anaconda3/envs/mmlab/include/python3.7m -c Correlation_Module/correlation.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/shankaiyu/anaconda3/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/shankaiyu/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shankaiyu/anaconda3/envs/mmlab/include/python3.7m -c Correlation_Module/correlation_sampler.cpp -o build/temp.linux-x86_64-3.7/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    Correlation_Module/correlation_sampler.cpp: In function ‘at::Tensor correlation_sample_forward(at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int)’:
    Correlation_Module/correlation_sampler.cpp:29:83: error: ‘TORCH_CHECK’ was not declared in this scope
     define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), x, " must be a CUDA tensor")
                                                                                       ^
    Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
     define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                            ^
    Correlation_Module/correlation_sampler.cpp:63:5: note: in expansion of macro ‘CHECK_INPUT’
         CHECK_INPUT(input1);
         ^
    Correlation_Module/correlation_sampler.cpp: In function ‘std::vector<at::Tensor> correlation_sample_backward(at::Tensor, at::Tensor, at::Tensor, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t)’:
    Correlation_Module/correlation_sampler.cpp:29:83: error: ‘TORCH_CHECK’ was not declared in this scope
     define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), x, " must be a CUDA tensor")
                                                                                       ^
    Correlation_Module/correlation_sampler.cpp:31:24: note: in expansion of macro ‘CHECK_CUDA’
     define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
                            ^
    Correlation_Module/correlation_sampler.cpp:89:5: note: in expansion of macro ‘CHECK_INPUT’
         CHECK_INPUT(input1);
         ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/shankaiyu/anaconda3/envs/mmlab/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vz7ytcfu/spatial-correlation-sampler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vz7ytcfu/spatial-correlation-sampler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5f_7bmhn/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by ClementPinard** [comment]
for this problem, you need to update your torch version to 1.2, or change the `TORCH_*` occurences to `AT_*`

**Comment by shankyle** [comment]
Thanks for your quick reply! The second problem is solved by updating the torch version to 1.2! For the first problem, I download the 0.2.0 version of this code and tried again but got the same error with:
`python setup_cpu.py instal`
`running install
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext
/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py:171: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++) is not compatible with the compiler Pytorch was
built with for this platform, which is clang++ on darwin. Please
use clang++ to to compile your extension. Alternatively, you may
compile PyTorch from source using g++, and then you can also use
g++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
building 'spatial_correlation_sampler_backend' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sky/anaconda3/envs/mmlab/include -arch x86_64 -I/Users/sky/anaconda3/envs/mmlab/include -arch x86_64 -I/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include -I/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/TH -I/Users/sky/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/include/THC -I/Users/sky/anaconda3/envs/mmlab/include/python3.7m -c Correlation_Module/correlation.cpp -o build/temp.macosx-10.7-x86_64-3.7/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
clang: error: unsupported option '-fopenmp'
error: command 'gcc' failed with exit status 1`

I am trying what #26 has done.

**Comment by ClementPinard** [comment]
Apparently the openMP headers are not properly installed. As tested by #26, you can try to apply what is said [here](https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave/55588705#55588705)

**Comment by shankyle** [comment]
Thanks for your advice!
I have tried a lot of methods but all failed(including tried   
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` )
I am sure it was the problem of GCC and I have used the python interpreter on my remote server to debug my code. Thanks for your help again!
