### ISSUE TITLE
WITHIN_BOUNDS x/y bug

### ISSUE THREAD

**Issue by aharley** [ClementPinard/Pytorch-Correlation-extension#33]
I noticed a discrepancy between the cpu and gpu code:
correlation.cpp says:
`WITHIN_BOUNDS(x, y, H, W) (x >= 0 && x < W && y >= 0 && y < H)`
correlation_cuda_kernel.cu says:
`WITHIN_BOUNDS(x, y, H, W) (x >= 0 && x < H && y >= 0 && y < W)`
I think this is a bug but maybe it does not affect anything.

**Comment by ClementPinard** [comment]
Thanks for spotting it ! fixed
