### ISSUE TITLE
Hello,can I modify this code to implement my own function？

### ISSUE THREAD

**Issue by CXMANDTXW** [ClementPinard/Pytorch-Correlation-extension#34]
The original correlation operation was performed in a nearby area.For example,FlowNetC is d=4,so the cost volume is HxWx81,Now I want to change the matching area to a fixed area.This fixed patch's size is hxw,so the cost volume is HxWx(hxw). Can I implement this by modifying this code?
Looking forward to your suggestions

**Comment by ClementPinard** [comment]
Wouldn't if be simpler to have a little python function to compute ideal patch sizes (h and w) that have your area ?

Since this module is downloadable directly from pip, you would have less troubles to share your work that way.

Otherwise, yes it's probably very easy to do.

**Comment by CXMANDTXW** [comment]
I have already finished this work,thank you.
