### ISSUE TITLE
Segmentation fault (core dumped) when running `check.py`

### ISSUE THREAD

**Issue by ysnan** [ClementPinard/Pytorch-Correlation-extension#36]
Hi, I have successfully installed via `pip install spatial-correlation-sampler`, but it could not pass the testing when I run `python check.py forward`. The error message are following:

> $ python check.py forward
Forward: CPU vs. CUDA ... Traceback (most recent call last):
  File "check.py", line 91, in <module>
    check_forward(input1, input2, correlation_sampler, args.verbose)
  File "check.py", line 35, in check_forward
    check_equal(cpu_values, cuda_values, verbose)
  File "check.py", line 18, in check_equal
    np.testing.assert_allclose(x, y, err_msg="Index: {}".format(i))
  File "/home/ysnan/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/ysnan/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0
Index: 0
(mismatch 39.64334705075446%)
 x: array([[[[  0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00,
            0.000000e+00,   0.000000e+00,   0.000000e+00,   0.000000e+00,
            0.000000e+00],...
 y: array([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],...
Segmentation fault (core dumped)

FYI, my configuration is 
gcc=7.4.0
pytorch=1.3.1
cuda=V10.0.130
python=3.6.3

Could you please help me to find out the solution. Thank you!

**Comment by ClementPinard** [comment]
It is very surprising that your array is full of zeros.

In the mean time, since the system tries compute the relative difference between 0 and 0, you are bound to have weird numbers, even if the absolute eror is practically 0.

Did you change the `check.py` file especially at line 75 and 79 ?

**Comment by ysnan** [comment]
Hi, I did not change anything of that file. I installed the package and did the checking right away. I just guess that the problem comes from the incompatibility with the new version of pytorch.

**Comment by ClementPinard** [comment]
how did you get the check.py file ? Did you clone the github repo ? Is it up to date ?

I just tried with pytorch 1.4 with a fresh install and it worked

**Comment by ysnan** [comment]
I also tried to use pytorch 1.4 with a fresh install, use `git install spatial-correlation-sampler` to install the package and use `git clone https://github.com/ClementPinard/Pytorch-Correlation-extension` to get the `check.py`. It turns out to be another problem:

> $ python check.py forward
Traceback (most recent call last):
  File "check.py", line 8, in <module>
    from spatial_correlation_sampler import SpatialCorrelationSampler
  File "/home/ysnan/anaconda3/envs/torch_latest/lib/python3.6/site-packages/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, spatial_correlation_sample
  File "/home/ysnan/anaconda3/envs/torch_latest/lib/python3.6/site-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: /home/ysnan/anaconda3/envs/torch_latest/lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

I guess the problem came from the incompatibility with `gcc` version?

**Comment by ClementPinard** [comment]
I have the same gcc version as you. :thinking: 
I guess here the problem is deeper that just this module.

Can you try to compile the official tutorial and see if it works ?
https://github.com/pytorch/extension-cpp

**Comment by ysnan** [comment]
The problem has been solved! Following the guideline you referred, I used `python setup.py install` to install the package, it passed with no error. But the weird thing is why the `pip` approach did not work. 

Anyway, thank you for your help!
