### ISSUE TITLE
I installed the version 0.0.8 successfully, but got an import error.

### ISSUE THREAD

**Issue by zfrruirui** [ClementPinard/Pytorch-Correlation-extension#37]
I use the following command to install the package.
`pip install spatial-correlation-sampler==0.0.8`
And got the success message:
`Processing ./.cache/pip/wheels/38/3b/a9/f9d27368124ec8ef31c510fdfd7e36739daa191f1015230a7d/spatial_correlation_sampler-0.0.8-cp37-cp37m-linux_x86_64.whl
Requirement already satisfied: torch>=0.4.1 in ./anaconda3/envs/corrflow/lib/python3.7/site-packages (from spatial-correlation-sampler==0.0.8) (1.1.0)
Requirement already satisfied: numpy in ./anaconda3/envs/corrflow/lib/python3.7/site-packages (from spatial-correlation-sampler==0.0.8) (1.17.5)
Installing collected packages: spatial-correlation-sampler
Successfully installed spatial-correlation-sampler-0.0.8`

But when I try to import the package, I got the following **error**.

>>> import torch
>>> import spatial_correlation_sampler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/remote-home/zhufangrui18210980021/anaconda3/envs/corrflow/lib/python3.7/site-packages/spatial_correlation_sampler/__init__.py", line 1, in <module>
    from .spatial_correlation_sampler import SpatialCorrelationSampler, SpatialCorrelationSamplerFunction, spatial_correlation_sample
  File "/remote-home/zhufangrui18210980021/anaconda3/envs/corrflow/lib/python3.7/site-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 6, in <module>
    import spatial_correlation_sampler_backend as correlation
ImportError: /remote-home/zhufangrui18210980021/anaconda3/envs/corrflow/lib/python3.7/site-packages/spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

My environment settings are:
- gcc: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
- torch: 1.1.0
- CUDA: 9.0, V9.0.176
- python: 3.7 

Could anyone help me to check what's wrong with it?
Thank you !!!

**Comment by zfrruirui** [comment]
I've solved this by changing the file `spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so`. And this setting is work for using spatial correlation sampler(version 0.0.8) :)

**Comment by SuhongWang** [comment]
> I've solved this by changing the file `spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so`. And this setting is work for using spatial correlation sampler(version 0.0.8) :)

May I ask how to change the file? I'm facing the same problem.

**Comment by ClementPinard** [comment]
You should try to install directly from source with `python setup.py install` . You may have a clearer log.

**Comment by SuhongWang** [comment]
> You should try to install directly from source with `python setup.py install` . You may have a clearer log.

Thanks for your reply!
I have solved this by reinstall pytorch 1.3.0 with CUDA10.1.
