### ISSUE TITLE
Link is not available

### ISSUE THREAD

**Issue by 2a2a** [ClementPinard/Pytorch-Correlation-extension#39]
Thank you for your great work! But the link below is not available now. I'll be grateful if you correct this error.

The backward pass of NVIDIA is not entirely correct when stride1 > 1 and kernel_size > 1, because not everything is computed, see here.

This is the original link address:
https://github.com/NVIDIA/flownet2-pytorch/blob/master/networks/correlation_package/src/correlation_cuda_kernel.cu#L120

**Comment by ClementPinard** [comment]
Hi, the link is available here : https://github.com/NVIDIA/flownet2-pytorch/blob/master/networks/correlation_package/correlation_cuda_kernel.cu

Not what exact part of the code I was pointing though, sorry.
