### ISSUE TITLE
How to use it in DispNet?

### ISSUE THREAD

**Issue by sczhou** [ClementPinard/Pytorch-Correlation-extension#4]
good job!
but how can I use it in dispnet? which only consider the disparity in the single axis.

Best and thanks.

**Comment by ClementPinard** [comment]
As a matter of fact compared to original correlation implementation, you can !
Consider the parameters in FlowNetC : `k=1, patch=21, stride=1, padding=0, dilation_patch=2`
The parameters can acutally accept a tuple of H and W values. So an equivalent correlation module for DispNet would be
`k=1, patch=(1,21), paddinf=0, dilation_patch=2`

My guess is that the Lab that created the correlation module (LMB Freiburg) uses DispNetS in all kind of big projects and never felt the need to make 1D Correlation Module, so it may not be as interesting as it is for FlowNetC, but you can try !

Clément

**Comment by ClementPinard** [comment]
Yes. You can try with a toy problem, but normally you should end up with a `B x 1 x 21 x H x W` tensor, which you can just squeeze into a `B x 21 x H x W` tensor and feed it to the rest of your network.

**Comment by sczhou** [comment]
Ok, I'll try it, thanks!
