### ISSUE TITLE
Why use `correlation_forward_cpp` instead of `correlation_backward_cpp`

### ISSUE THREAD

**Issue by hangtingchen** [ClementPinard/Pytorch-Correlation-extension#43]
Hi,
First, thanks a lot for your code. I have learnt a lot from it. I have found that the following line for cpu uses `correlation_forward_cpp` instead of `correlation_backward_cpp`
https://github.com/ClementPinard/Pytorch-Correlation-extension/blob/ca4e32614e1245c1d7417b27c0428774f7efb72a/Correlation_Module/correlation.cpp#L143
Is this a bug or other things I don't know?

**Comment by hangtingchen** [comment]
Sorry. When compiling, it says
![微信截图_20200801110748](https://user-images.githubusercontent.com/30209378/89092760-42369180-d3e7-11ea-97d0-a954da877e57.png)
I defined the backward and forward function, but why did the complier unrecognize them ?

**Comment by ClementPinard** [comment]
Ah good catch ! It's a silent bug. Apparently it's not a problem if you use use to dispatch calls with the same name, maybe it wasn't a problem thanks to the fact that dispatched functions don't have the same argument and thus a different prototype even if they share the same name.

I'm not able to change it right now but if you make a or i'd be happy to merge it

**Comment by hangtingchen** [comment]
#44
