### ISSUE TITLE
Can't install through pip after update to 0.3

### ISSUE THREAD

**Issue by shreyas23** [ClementPinard/Pytorch-Correlation-extension#51]
Hey @ClementPinard!

Starting yesterday after the update to the codebase, I stopped being able to install this on my system with specs:

Ubuntu 18.04
CUDA 10.0
gcc 7.4.0

The issue is similar to with an nvcc error in #1 

Any ideas? Downgrading back to 0.2.1 works fine. 

Error log:

    Correlation_Module/correlation_cuda_kernel.cu(23): error: PackedTensorAccessor32 is not a template

    Correlation_Module/correlation_cuda_kernel.cu(24): error: PackedTensorAccessor32 is not a template

    Correlation_Module/correlation_cuda_kernel.cu(25): error: PackedTensorAccessor32 is not a template

    Correlation_Module/correlation_cuda_kernel.cu(88): error: PackedTensorAccessor32 is not a template

    Correlation_Module/correlation_cuda_kernel.cu(89): error: PackedTensorAccessor32 is not a template

    Correlation_Module/correlation_cuda_kernel.cu(90): error: PackedTensorAccessor32 is not a template

    Correlation_Module/correlation_cuda_kernel.cu(161): error: PackedTensorAccessor32 is not a template

    Correlation_Module/correlation_cuda_kernel.cu(162): error: PackedTensorAccessor32 is not a template

    Correlation_Module/correlation_cuda_kernel.cu(163): error: PackedTensorAccessor32 is not a template

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "PackedTensorAccessor32" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "trInput1_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "trInput2_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "output_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "PackedTensorAccessor32" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "trInput1_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "trInput2_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "output_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "PackedTensorAccessor32" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "trInput1_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "trInput2_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: identifier "output_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(262): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(262): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(262): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(262): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(297): error: identifier "PackedTensorAccessor32" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(297): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(297): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(297): error: identifier "input1_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(297): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(297): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(297): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(297): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(297): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(297): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(297): error: identifier "input2_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(297): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(297): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(297): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(297): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(297): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(297): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(297): error: identifier "gradInput1_acc" is undefined

    Correlation_Module/correlation_cuda_kernel.cu(297): error: class "at::Tensor" has no member "packed_accessor32"

    Correlation_Module/correlation_cuda_kernel.cu(297): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(297): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(297): error: expected an expression

    Correlation_Module/correlation_cuda_kernel.cu(297): error: type name is not allowed

    Correlation_Module/correlation_cuda_kernel.cu(297): error: argument list for class template "at::RestrictPtrTraits" is missing

    Correlation_Module/correlation_cuda_kernel.cu(297): error: identifier "gradInput2_acc" is undefined

    Error limit reached.
    100 errors detected in the compilation of "/tmp/tmpxft_00000441_00000000-6_correlation_cuda_kernel.cpp1.ii".
    Compilation terminated.
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by ClementPinard** [comment]
What is your pytorch version?

PackedTensorAccessor32 is a new feature, and the one I used before has been deprecated for pytorch 1.6

**Comment by shreyas23** [comment]
Ah I see, I'm using 1.2.0 so that's explains it. Thanks for the quick response!
