### ISSUE TITLE
Error running module on GPU

### ISSUE THREAD

**Issue by BK1024** [ClementPinard/Pytorch-Correlation-extension#6]
Hi Clement, I have been using your spatial-correlation-sampler. When I run `python grad_check cpu` it returns 'ok' but with backend option set as cuda, I get the following error:

Traceback (most recent call last):
  File "grad_check.py", line 41, in <module>
    if gradcheck(correlation_sampler, [input1, input2]):
  File "/home/bowen/anaconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 190, in gradcheck
    output = _differentiable_outputs(func(*inputs))
  File "/home/bowen/anaconda3/lib/python3.6/site-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 73, in forward
    dH, dW)
RuntimeError: sizes must be non-negative (THCTensor_resizeNd at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCTensor.cpp:108)
frame #0: THCudaDoubleTensor_newWithStorage + 0xfa (0x7fe7c042c9aa in /home/bowen/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #1: at::CUDADoubleType::th_tensor(at::ArrayRef<long>) const + 0xa5 (0x7fe7c02cf4e5 in /home/bowen/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: at::native::tensor(at::Type const&, at::ArrayRef<long>) + 0x3a (0x7fe7e34c37da in /home/bowen/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #3: at::Type::tensor(at::ArrayRef<long>) const + 0x9 (0x7fe7e36b1b69 in /home/bowen/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #4: torch::autograd::VariableType::tensor(at::ArrayRef<long>) const + 0x44 (0x7fe7e5333d04 in /home/bowen/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #5: at::native::zeros(at::ArrayRef<long>, at::TensorOptions const&) + 0x31 (0x7fe7e351a651 in /home/bowen/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #6: <unknown function> + 0x231f9 (0x7fe7bca6e1f9 in /home/bowen/anaconda3/lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so)
frame #7: correlation_cuda_forward(at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int) + 0x167 (0x7fe7bca6f204 in /home/bowen/anaconda3/lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so)
frame #8: correlation_sample_forward(at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int) + 0x1b4 (0x7fe7bca60ed4 in /home/bowen/anaconda3/lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x217b9 (0x7fe7bca6c7b9 in /home/bowen/anaconda3/lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x1fc2d (0x7fe7bca6ac2d in /home/bowen/anaconda3/lib/python3.6/site-packages/spatial_correlation_sampler_backend.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #18: THPFunction_do_forward(THPFunction*, _object*) + 0x2ad (0x7fe7e5310fbd in /home/bowen/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #35: __libc_start_main + 0xf5 (0x7fe7f9c8af45 in /lib/x86_64-linux-gnu/libc.so.6)

I also tried to pass some tensors into the module in the console. Calling forward and backward seems to be fine as long as computation is on cpu. The module crashes once I put the same tensor on GPU.

Code is running on Ubuntu 14.04. I am using anaconda python 3.6.5. My pytorch version is 0.4.1. And I am using CUDA 9.0.

It is worth mentioning that I had trouble installing the code, as I later discovered that nvcc is using gcc-6.0 which is incompatible with my CUDA 9.0 and I redirected the softlink to gcc-4.9. By doing this I am able to compile and install. Not sure if it is related to this crash. 

Please let me know what you think. Thank you!

**Comment by ClementPinard** [comment]
Hey, thanks for using this module.
I encountered this error before, but interestingly, it was for CPU tensors that I had problems.
So the problem is confusion about what intList is about, are they signed or not ? And depending on your compiler it might or might not be what you expect.

See how diffrently I constructed the tensor in [CPU](https://github.com/ClementPinard/Pytorch-Correlation-extension/blob/master/Correlation_Module/correlation.cpp#L89:L91), and in [CUDA](https://github.com/ClementPinard/Pytorch-Correlation-extension/blob/master/Correlation_Module/correlation_cuda_kernel.cu#L247:L255).
Namely, construct first an intList and then passing it as argument did not work compared to giving directly the array, so there might be something wrong with the intList constructor.

Anyway, what I advise you is to try to replace the CUDA code with the CPU code regarding the intList argument, and see how it goes.
If it works for you, I'll push a patch.

Clément

**Comment by BK1024** [comment]
Hi Clement, It works! Both 'cpu' and 'cuda' returns 'ok' for grad_check.py. Is there any further test that I can run at this point? Or I am off to go? 

I think you are correct about the intList. Not sure why this is happening though. 

Just out of curiosity, what is the version of nvcc and gcc this package is built to compile on? Or what is the version you used for developing this code? Thank you!

Bowen

**Comment by BK1024** [comment]
Thank you for replying. I may have found out about what is going on. I am using the SpatialCorrelationSampler, which is cuda module wrapped in a pytorch module wrapper. I put it as a submodule of my PWC net `model = PWC()` by `self.corr = SpatialCorrelationSampler()`. 

However, by doing `model.to(cuda_id)` does not put `self.corr` on GPU and by calling `self.corr(input1, input2)` crashes the program. So I manually did `self.corr = self.corr.to(cuda_id)` to fix it. 

This is very weird from to the best of my knowledge. As this module has no learnable parameters, there is no need to put it on GPU (like MSELoss()).

**Comment by ClementPinard** [comment]
So it's a problem with the module. I'll investigate that to see what's wrong !

In the mean time you can use it as a function, so you don't even need to make it an attribute of PWC, just like you would call from torch.nn.functional inside the forward function !

**Comment by BK1024** [comment]
Sure. Thank you so much for helping out! My PWC net is training now. I will let you know if I discovered any further problems.

**Comment by BK1024** [comment]
Hi Clement, I am so sorry. Ignore what I have said before about the error. So I have further tested my script, it is not about module. **SpatialCorrelationSampler only works on with cuda device set to 0**. I have not yet tried to manually set visible GPU ids from CUDA side and see what happens.

**Comment by ClementPinard** [comment]
Well if it works only on GPU 0 it's a problem ! Unfortunately I don't have a second GPU to do thorough tests

Are you saying that when the input tensor is in e.g GPU1it crash immediately or does it take a few iterations, backward included ?

**Comment by BK1024** [comment]
It crashes immediately in forward computation.

**Comment by ClementPinard** [comment]
And does it work when using the function ? Is the problem only related to the module ?

Becsue the `.to` operation should not actually do anything for this module since the forward is just a wrapper to the function !

**Comment by tonyzzzt** [comment]
>           Hi Clement, It works! Both 'cpu' and 'cuda' return 'ok' for grad_check.py. Is there any further test that I can run at this point? Or I am off to go?
> I think you are correct about the intList. Not sure why this is happening though.
> Just out of curiosity, what is the version of nvcc and gcc this package is built to compile on? Or what is the version you used for developing this code? Thank you!
> Bowen

Hello！And I want to know what did you modify with it that it can run  on GPU. Thanks

**Comment by ClementPinard** [comment]
the problem was the output tensor creation. More specifically, the IntList object may not be treated the same, depending on your nvcc version (it's a guess).

So at first I was constructing an explicit IntList (special objects for dealing with array sizes in ATen) from a table of integers, but now we directly pass the table of integers as an argument instead of the IntList to let the function take care of the conversion for us.

Last version of the code include these updates. If you want to know what has been changed exactly, you can look at this commit : https://github.com/ClementPinard/Pytorch-Correlation-extension/commit/fe8c47c0be0223b8f661477c68cf069b7665ac42

**Comment by tonyzzzt** [comment]
### I'm sorry ,but it still can't work on GPU and raise this error:
Traceback (most recent call last):
  File "grad_check.py", line 41, in <module>
    if gradcheck(correlation_sampler, [input1, input2]):
  File "/home/tong2018234172/anaconda2/lib/python2.7/site-packages/torch/autograd/gradcheck.py", line 190, in gradcheck
    output = _differentiable_outputs(func(*inputs))
  File "/home/tong2018234172/anaconda2/lib/python2.7/site-packages/spatial_correlation_sampler/spatial_correlation_sampler.py", line 73, in forward
    dH, dW)
RuntimeError: sizes must be non-negative (THCTensor_resizeNd at /opt/conda/conda-bld/pytorch_1532571898140/work/aten/src/THC/THCTensor.cpp:108)
frame #0: THCudaDoubleTensor_newWithStorage + 0xfa (0x7f1a479c6c4a in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #1: at::CUDADoubleType::th_tensor(at::ArrayRef<long>) const + 0xa5 (0x7f1a47869775 in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: at::native::tensor(at::Type const&, at::ArrayRef<long>) + 0x3a (0x7f1a639ff7da in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so)
frame #3: at::Type::tensor(at::ArrayRef<long>) const + 0x9 (0x7f1a63bedb69 in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so)
frame #4: torch::autograd::VariableType::tensor(at::ArrayRef<long>) const + 0x44 (0x7f1a65866474 in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/torch/_C.so)
frame #5: at::native::zeros(at::ArrayRef<long>, at::TensorOptions const&) + 0x31 (0x7f1a63a56651 in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/torch/lib/libcaffe2.so)
frame #6: <unknown function> + 0x23569 (0x7f1a43900569 in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/spatial_correlation_sampler_backend.so)
frame #7: correlation_cuda_forward(at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int) + 0x167 (0x7f1a43901574 in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/spatial_correlation_sampler_backend.so)
frame #8: correlation_sample_forward(at::Tensor, at::Tensor, int, int, int, int, int, int, int, int, int, int) + 0x1b4 (0x7f1a438f2f04 in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/spatial_correlation_sampler_backend.so)
frame #9: <unknown function> + 0x21b89 (0x7f1a438feb89 in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/spatial_correlation_sampler_backend.so)
frame #10: <unknown function> + 0x1ff5d (0x7f1a438fcf5d in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/spatial_correlation_sampler_backend.so)
<omitting python frames>
frame #18: THPFunction_do_forward(THPFunction*, _object*) + 0x2ad (0x7f1a6584360d in /home/tong2018234172/anaconda2/lib/python2.7/site-packages/torch/_C.so)
frame #31: __libc_start_main + 0xf5 (0x7f1a7c87bf45 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by ClementPinard** [comment]
what argument did you call the function with ?

What is your CUDA version ? gcc version ? Does it work with python3 ?

**Comment by tonyzzzt** [comment]
gcc version 4.9.4  
cuda version 8.0 

but I haven't test it on python3

**Comment by ClementPinard** [comment]
Just tested on a docker with cuida 8.0 , pytorch 1.0 for cuda8.0 and gcc 4.9 and it went fine.
Have you got everything up to date ?

**Comment by tonyzzzt** [comment]
I will update my softworks .Thank you for your patient answer !

**Comment by jbohnslav** [comment]
Hello,

Thanks for your excellent work on this package! I've also found that I get an illegal memory access error when using any GPU ID other than 0. Weirdly, this happens when I try to serialize the model, using `torch.save`:

```
THCudaCheck FAIL file=/home/jim/Documents/python/pytorch/torch/csrc/generic/serialization.cpp line=15 error=77 : an illegal memory access was encountered51s/it]
Traceback (most recent call last):
  File "train.py", line 326, in <module>
    main()
  File "train.py", line 221, in main
    torch.save(state, fullfile)
  File ".../anaconda3/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 219, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File ".../anaconda3/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 144, in _with_file_like
    return body(f)
  File ".../anaconda3/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 219, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File ".../anaconda3/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 298, in _save
    serialized_storages[key]._write_file(f, _should_read_directly(f))
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at .../pytorch/torch/csrc/generic/serialization.cpp:15
```

Python: 3.7.1
GCC: 7.3.0
Ubuntu 18.04.1
Pytorch: 1.1.0a0+10c10b0
CUDA: 10.0.130
Nvidia driver version: 410.79

**Comment by ClementPinard** [comment]
This multi gpu error really seems to be an annoying error.

I don't have a multi GPU setup unfortunately. I'm putting a "help wanted" label to signify that someone else than me needs to work on this (or maybe let me access to a multi gpu steup :p )

**Comment by yuanhaitao** [comment]
> Hello,
> 
> Thanks for your excellent work on this package! I've also found that I get an illegal memory access error when using any GPU ID other than 0. Weirdly, this happens when I try to serialize the model, using `torch.save`:
> 
> ```
> THCudaCheck FAIL file=/home/jim/Documents/python/pytorch/torch/csrc/generic/serialization.cpp line=15 error=77 : an illegal memory access was encountered51s/it]
> Traceback (most recent call last):
>   File "train.py", line 326, in <module>
>     main()
>   File "train.py", line 221, in main
>     torch.save(state, fullfile)
>   File ".../anaconda3/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 219, in save
>     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
>   File ".../anaconda3/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 144, in _with_file_like
>     return body(f)
>   File ".../anaconda3/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 219, in <lambda>
>     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
>   File ".../anaconda3/envs/pt/lib/python3.7/site-packages/torch/serialization.py", line 298, in _save
>     serialized_storages[key]._write_file(f, _should_read_directly(f))
> RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at .../pytorch/torch/csrc/generic/serialization.cpp:15
> ```
> Python: 3.7.1
> GCC: 7.3.0
> Ubuntu 18.04.1
> Pytorch: 1.1.0a0+10c10b0
> CUDA: 10.0.130
> Nvidia driver version: 410.79

hello, have you solved the issue?

**Comment by ClementPinard** [comment]
Not yet. I don't have a multi GPU rig, do I can't reproduce the bug :(

Maybe you can try to put it in GPU0 before saving it ? Anyway I highly recommend you to use the functional instead of the module so that the serialization tool won't try to save it. It's parameter less so there's no need saving it.

**Comment by ClementPinard** [comment]
FINALLY fixed, thanks @InnovArul !
