### ISSUE TITLE
Faile to install spatial-correlation-sampler

### ISSUE THREAD

**Issue by Heeenry** [ClementPinard/Pytorch-Correlation-extension#64]
hi there, 
 I encountered some errors,when I tried with "pip install spatial-correlation-sampler -vvv".Please help me.
cuda version: 10.1.168
pytorch version:1.7.1
python version:3.7.0
gcc 7.5.0
[2.txt](https://github.com/ClementPinard/Pytorch-Correlation-extension/files/5762788/2.txt)

**Comment by Heeenry** [comment]
Ubuntu 16.04

**Comment by DengueTim** [comment]
Same on Ubuntu 18.04, pytouch 1.8..

**Comment by DengueTim** [comment]
cloning [](https://github.com/Minwellcym/Pytorch-Correlation-extension) and running `python setup.py install` worked...

**Comment by usbhub** [comment]
I think this is the same issue as: https://github.com/ClementPinard/Pytorch-Correlation-extension/issues/52

Just installing using this repo at the master branch works (there was a fix pushed to 1.7 / master branch but it's not in pypi yet) 

`sudo pip3 install git+https://github.com/ClementPinard/Pytorch-Correlation-extension`

I'm using pytorch 1.7.1 and the above command worked for me.

**Comment by ClementPinard** [comment]
Ah yes, sorry, I didn't update the pypi repo yet. I'll do it as soon as possible.

**Comment by bamboopu** [comment]
> cloning https://github.com/Minwellcym/Pytorch-Correlation-extension and running `python setup.py install` worked...

It works for me. Thanks a lot!
--------
Ubuntu 20.03.3
RTX 3090
CUDA 11.0
cudnn 11.1
python 3.7.11
torch 1.8.0+cu111
torchvision 0.9.0+cu111
