### ISSUE TITLE
the output is nan in fp16

### ISSUE THREAD

**Issue by beryl000** [ClementPinard/Pytorch-Correlation-extension#65]
I use correlation layer in my model. When I set the input to float16,  the output Tensor has some nan elements:

tensor([[[[-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          ...,
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -7.8674e-02,
           -7.9041e-02, -7.9834e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -7.6843e-02,
           -7.7148e-02, -7.8796e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -7.6782e-02,
           -7.7026e-02, -7.7881e-02]],

         [[-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          ...,
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -7.9529e-02,
           -8.0078e-02, -7.9834e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -7.7759e-02,
           -7.7637e-02, -7.8796e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -7.7026e-02,
           -7.7393e-02, -7.8552e-02]],

         [[-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          ...,
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -7.8979e-02,
           -7.5195e-02, -7.5378e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -7.7332e-02,
           -7.4829e-02, -7.5012e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -7.7820e-02,
           -7.5378e-02, -7.5439e-02]],

         ...,

         [[-2.5574e-02, -5.5923e-03,  5.5603e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-6.9199e-03,  2.1570e-01,  4.4409e-01,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [ 6.4735e-03,  5.0049e-01,  5.9424e-01,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          ...,
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02]],

         [[-2.5314e-02,  5.3619e-02,  2.2424e-01,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-5.8594e-03,  3.8159e-01,  5.4785e-01,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-5.8594e-03,  3.9160e-01,  5.3418e-01,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          ...,
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02]],

         [[-1.7776e-02,  8.4167e-02,  1.8848e-01,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-4.1533e-04,  4.0625e-01,  5.3662e-01,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-9.4452e-03,  3.7378e-01,  5.9814e-01,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          ...,
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02],
          [-8.1299e-02, -8.1299e-02, -8.1299e-02,  ..., -8.1299e-02,
           -8.1299e-02, -8.1299e-02]]],

        [[[-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          ...,
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.3844e-02,
           -3.3844e-02, -3.3966e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.3844e-02,
           -3.3844e-02, -3.3966e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.3966e-02,
           -3.3966e-02, -3.4058e-02]],

         [[-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          ...,
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.3844e-02,
           -3.3844e-02, -3.3936e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.3844e-02,
           -3.3844e-02, -3.3966e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.3966e-02,
           -3.3966e-02, -3.4058e-02]],

         [[-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          ...,
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.3813e-02,
           -3.3569e-02, -3.3020e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.3844e-02,
           -3.3478e-02, -3.3051e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.3966e-02,
           -3.3722e-02, -3.3386e-02]],

         ...,

         [[-2.9907e-02, -2.8366e-02, -3.0365e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-2.9800e-02, -2.8046e-02, -2.9663e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-2.8824e-02, -2.6016e-02, -2.7847e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          ...,
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02]],

         [[-3.1830e-02, -3.2837e-02, -3.3478e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.2379e-02, -3.1143e-02, -3.1021e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.0731e-02, -2.7725e-02, -2.6062e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          ...,
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02]],

         [[-3.3966e-02, -3.4058e-02, -3.4058e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.2745e-02, -3.1311e-02, -3.1921e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-2.9831e-02, -2.7115e-02, -2.9587e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          ...,
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02],
          [-3.4424e-02, -3.4424e-02, -3.4424e-02,  ..., -3.4424e-02,
           -3.4424e-02, -3.4424e-02]]],

        [[[-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          ...,
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -2.8870e-02,
           -2.9602e-02, -3.1052e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -2.9724e-02,
           -3.0334e-02, -3.1174e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.1311e-02,
           -3.1342e-02, -3.1616e-02]],

         [[-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          ...,
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.0731e-02,
           -3.1494e-02, -3.1830e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.0777e-02,
           -3.1769e-02, -3.2013e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.1525e-02,
           -3.1891e-02, -3.2104e-02]],

         [[-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          ...,
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.1647e-02,
           -3.1006e-02, -3.0945e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.1891e-02,
           -3.1586e-02, -3.1433e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2013e-02,
           -3.2013e-02, -3.1799e-02]],

         ...,

         [[-3.2196e-02, -3.2104e-02, -3.2074e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.1982e-02, -3.1708e-02, -3.1891e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.1891e-02, -3.1433e-02, -3.1860e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          ...,
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02]],

         [[-3.2257e-02, -3.2074e-02, -3.2074e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2135e-02, -3.1891e-02, -3.1891e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2135e-02, -3.1891e-02, -3.1891e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          ...,
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02]],

         [[-3.2257e-02, -3.2074e-02, -3.2074e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2135e-02, -3.1891e-02, -3.1891e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2135e-02, -3.1891e-02, -3.1891e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          ...,
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02],
          [-3.2410e-02, -3.2410e-02, -3.2410e-02,  ..., -3.2410e-02,
           -3.2410e-02, -3.2410e-02]]],

        [[[        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          ...,
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan]],

         [[        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          ...,
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan]],

         [[        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          ...,
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan]],

         ...,

         [[        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          ...,
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan]],

         [[        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          ...,
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan]],

         [[        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          ...,
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan],
          [        nan,         nan,         nan,  ...,         nan,
                   nan,         nan]]]], device='cuda:3', dtype=torch.float16,
       grad_fn=<LeakyReluBackward1>)

**Comment by ClementPinard** [comment]
Hi, sorry for the delay.
Is the model running fine in fp32 ? Is the model running fine when only using 1 gpu ?
