### ISSUE TITLE
Unknown CUDA Arch (8.6) or GPU not supported

### ISSUE THREAD

**Issue by Vandermode** [ClementPinard/Pytorch-Correlation-extension#66]
Hi, It looks like this module cannot be compiled in GTX 3090 GPU.
I was wondering if there is a way to address this issue?
Thank you very much!

**Comment by ClementPinard** [comment]
Hi,
not an owner of GTX3090 so I will struggle to help you properly, but you can have a look at this issue : #61 
From what I understood, the solution is simply to update to pytorch nightly.

Good luck !

**Comment by SBaokun** [comment]
i meet the same problem ,have you slove it??
thanks!!!
