### ISSUE TITLE
Can you help me solve the problem I encountered? Thank you

### ISSUE THREAD

**Issue by zouzhiwei217** [ClementPinard/Pytorch-Correlation-extension#67]
ERROR: Command errored out with exit status 1:
     command: /usr/wzc/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_35387be2de634ec0b35b241a777e94a7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_35387be2de634ec0b35b241a777e94a7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8uvd47su
         cwd: /tmp/pip-install-konxfc5l/spatial-correlation-sampler_35387be2de634ec0b35b241a777e94a7/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-konxfc5l/spatial-correlation-sampler_35387be2de634ec0b35b241a777e94a7/setup.py", line 2, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/73/99/fbfcb914944c390e59aefd29c17fba2dd7d647a8b58385ca39ed0a32765f/spatial_correlation_sampler-0.3.0.tar.gz#sha256=134a8818fd61e21345c1e245baf152d4f255940dc9a8457fc090e7d724c9824d (from https://pypi.tuna.tsinghua.edu.cn/simple/spatial-correlation-sampler/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/69/62/96bda9bf47f2a2ea978ec86a2e0ac3631036e6650d02ee81ba769d8d5dae/spatial_correlation_sampler-0.2.1.tar.gz (8.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/wzc/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_ee3f1d3151154cc181474e995cc6565b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_ee3f1d3151154cc181474e995cc6565b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e0hv_1bu
         cwd: /tmp/pip-install-konxfc5l/spatial-correlation-sampler_ee3f1d3151154cc181474e995cc6565b/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-konxfc5l/spatial-correlation-sampler_ee3f1d3151154cc181474e995cc6565b/setup.py", line 2, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/69/62/96bda9bf47f2a2ea978ec86a2e0ac3631036e6650d02ee81ba769d8d5dae/spatial_correlation_sampler-0.2.1.tar.gz#sha256=9a699c5a68359a161311fc3b4bb615cfab173b9b98ea1f8c627f0cc394f30831 (from https://pypi.tuna.tsinghua.edu.cn/simple/spatial-correlation-sampler/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0e/81/37a407309ba447a7a710d74aa06bfcfed29f160862d824d76e7cdbae57c7/spatial_correlation_sampler-0.2.0.tar.gz (8.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/wzc/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_ad087889224b40cba57f8af8d91479bd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_ad087889224b40cba57f8af8d91479bd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3h3nny42
         cwd: /tmp/pip-install-konxfc5l/spatial-correlation-sampler_ad087889224b40cba57f8af8d91479bd/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-konxfc5l/spatial-correlation-sampler_ad087889224b40cba57f8af8d91479bd/setup.py", line 2, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/0e/81/37a407309ba447a7a710d74aa06bfcfed29f160862d824d76e7cdbae57c7/spatial_correlation_sampler-0.2.0.tar.gz#sha256=d161f80f09eb1cda02fc27ec2ec785bfa115d05afc34001674c95010f5b5c462 (from https://pypi.tuna.tsinghua.edu.cn/simple/spatial-correlation-sampler/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a6/d1/aa0a71739ce998f655286d966c0ad7aff765648431c054c34db7d58b811b/spatial_correlation_sampler-0.1.0.tar.gz (7.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/wzc/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_d3bc4fd18ece4317ba205497c44d1f7d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_d3bc4fd18ece4317ba205497c44d1f7d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dat6vayq
         cwd: /tmp/pip-install-konxfc5l/spatial-correlation-sampler_d3bc4fd18ece4317ba205497c44d1f7d/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-konxfc5l/spatial-correlation-sampler_d3bc4fd18ece4317ba205497c44d1f7d/setup.py", line 2, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/a6/d1/aa0a71739ce998f655286d966c0ad7aff765648431c054c34db7d58b811b/spatial_correlation_sampler-0.1.0.tar.gz#sha256=897b0bb3c8c9c0c7e0fb6641b25eeaa8a00dac7ca7bf83452417243de5e715e3 (from https://pypi.tuna.tsinghua.edu.cn/simple/spatial-correlation-sampler/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/74/5d/e51bd2126527d7339025febcda13630f1423afc0d9c945806879d242eb80/spatial_correlation_sampler-0.0.8.tar.gz (7.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/wzc/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_12ad793e7ea74c2683d4d1199b4ca436/setup.py'"'"'; __file__='"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_12ad793e7ea74c2683d4d1199b4ca436/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bdzp80_h
         cwd: /tmp/pip-install-konxfc5l/spatial-correlation-sampler_12ad793e7ea74c2683d4d1199b4ca436/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-konxfc5l/spatial-correlation-sampler_12ad793e7ea74c2683d4d1199b4ca436/setup.py", line 2, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/74/5d/e51bd2126527d7339025febcda13630f1423afc0d9c945806879d242eb80/spatial_correlation_sampler-0.0.8.tar.gz#sha256=c4f1b72cb47c6160d24971ffcb69a8649c7af0b341b3069455924d3364abc5e2 (from https://pypi.tuna.tsinghua.edu.cn/simple/spatial-correlation-sampler/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b0/2b/f1d8d71a695f31e8d2f59ec9ec5824ecf3e253cf799c821b4c2067e392b2/spatial_correlation_sampler-0.0.5.tar.gz (6.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/wzc/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_78b8f230bd3c412d88d3f834d04f65a1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-konxfc5l/spatial-correlation-sampler_78b8f230bd3c412d88d3f834d04f65a1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kcajg6w9
         cwd: /tmp/pip-install-konxfc5l/spatial-correlation-sampler_78b8f230bd3c412d88d3f834d04f65a1/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-konxfc5l/spatial-correlation-sampler_78b8f230bd3c412d88d3f834d04f65a1/setup.py", line 2, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/b0/2b/f1d8d71a695f31e8d2f59ec9ec5824ecf3e253cf799c821b4c2067e392b2/spatial_correlation_sampler-0.0.5.tar.gz#sha256=adcd9846cbd0ed12717dd24e144bfe4813a6a7d59ac460fb97549cd44465fb4e (from https://pypi.tuna.tsinghua.edu.cn/simple/spatial-correlation-sampler/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement spatial-correlation-sampler
ERROR: No matching distribution found for spatial-correlation-sampler

**Comment by ClementPinard** [comment]
It seems that pytorch is not installed on your device. You need to install it before because correlation-sampler package dependencies need torch module.
