### ISSUE TITLE
Time measurement

### ISSUE THREAD

**Issue by buganini** [ClementPinard/Pytorch-Correlation-extension#69]
Shouldn't there be `torch.cuda.synchronize()` before every `time.time()` ?

**Comment by ClementPinard** [comment]
Not necessarily if you activate the environment variable `CUDA_LAUNCH_BLOCKING` before, why makes ever cuda call synchronous.

See https://pytorch.org/docs/stable/notes/cuda.html#asynchronous-execution

**Comment by buganini** [comment]
Thanks, just see that in README :+1:
