### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by jbohnslav** [ClementPinard/Pytorch-Correlation-extension#7]
Hello, 

I'd love to run FlowNet2 on my Windows machine. I tried `pip install spatial-correlation-sampler`, It gives me an extensive error message which ends: 
```
c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/host_config.h(133): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported!
    correlation_cuda_kernel.cu
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin\\nvcc.exe' failed with exit status 2
```

**Comment by ClementPinard** [comment]
Hello,
I'm sorry, I don't have a windows machine to test the building code on :(
Maybe this is related : https://github.com/pytorch/extension-cpp/issues/2

Can you try to compile the custom-extension-tutorial ?
