### ISSUE TITLE
fatal error: cuda.h: no such file or directory

### ISSUE THREAD

**Issue by CarsonLoong** [ClementPinard/Pytorch-Correlation-extension#70]
I run the "python setup.py install" with the code downloaded, and here are the error imformation:

running install
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'spatial_correlation_sampler_backend' extension
gcc -pthread -B /home/xinglongz/anaconda3/envs/pytracking/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include -I/home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include/TH -I/home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda:/usr/local/cuda/include -I/home/xinglongz/anaconda3/envs/pytracking/include/python3.8 -c Correlation_Module/correlation.cpp -o build/temp.linux-x86_64-3.8/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/xinglongz/anaconda3/envs/pytracking/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include -I/home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include/TH -I/home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda:/usr/local/cuda/include -I/home/xinglongz/anaconda3/envs/pytracking/include/python3.8 -c Correlation_Module/correlation_sampler.cpp -o build/temp.linux-x86_64-3.8/Correlation_Module/correlation_sampler.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h:7:0,
                 from /home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include/c10/cuda/CUDAGuard.h:3,
                 from Correlation_Module/correlation_sampler.cpp:2:
/home/xinglongz/anaconda3/envs/pytracking/lib/python3.8/site-packages/torch/include/c10/cuda/CUDAException.h:5:10: fatal error: cuda.h: no such file or directory
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

Thank you so much!

**Comment by CarsonLoong** [comment]
with CUDA 10 and gcc 7.5

**Comment by CarsonLoong** [comment]
I build a pycharm project and run it in pycharm, then everything goes all right !

**Comment by z-fy-31** [comment]
hi, i have the same problem with CUDA10.0 and gcc7.5.0 and torch1.8.1 and python3.8 .can you tell me whats your pytorch version?
