### ISSUE TITLE
Having problem in installing "spatial-correlation-sampler"

### ISSUE THREAD

**Issue by XiaoXueHou** [ClementPinard/Pytorch-Correlation-extension#72]
Dear friend, I have met problem during installing "spatial-correlation-sampler" when I used "pip install spatial-correlation-sampler". My environment is : python==3.6.8; cuda==9.0; pytorch=1.0.1(but it has been updated to 1.8.1 automatically during installing) gcc=5.4.0. Could you help me with the installation please? Here is the Error infomation:
(MotionSqueeze) lj@1080ti:~/Examples$ CC=gcc-5 CXX=g++-5 pip install spatial-correlation-sampler
Collecting spatial-correlation-sampler
  Using cached https://files.pythonhosted.org/packages/73/99/fbfcb914944c390e59aefd29c17fba2dd7d647a8b58385ca39ed0a32765f/spatial_correlation_sampler-0.3.0.tar.gz
Requirement already satisfied: torch>=1.1 in /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages (from spatial-correlation-sampler) (1.8.1)
Requirement already satisfied: numpy in /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages (from spatial-correlation-sampler) (1.17.2)
Requirement already satisfied: dataclasses; python_version < "3.7" in /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages (from torch>=1.1->spatial-correlation-sampler) (0.8)
Requirement already satisfied: typing-extensions in /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages (from torch>=1.1->spatial-correlation-sampler) (3.7.4.3)
Building wheels for collected packages: spatial-correlation-sampler
  Building wheel for spatial-correlation-sampler (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lj/software/anaconda3/envs/MotionSqueeze/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-967jjy22 --python-tag cp36
       cwd: /tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/
  Complete output (55 lines):
  /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
    return torch._C._cuda_getDeviceCount() > 0
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-9.0'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py", line 57, in <module>
      launch_setup()
    File "/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py", line 52, in launch_setup
      "Topic :: Scientific/Engineering :: Artificial Intelligence"
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 378, in build_extensions
      self._check_abi()
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 734, in _check_abi
      check_compiler_abi_compatibility(compiler)
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 282, in check_compiler_abi_compatibility
      if not check_compiler_ok_for_platform(compiler):
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 242, in check_compiler_ok_for_platform
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/subprocess.py", line 356, in check_output
      **kwargs).stdout
    File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/subprocess.py", line 438, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['which', 'g++-5']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for spatial-correlation-sampler
  Running setup.py clean for spatial-correlation-sampler
Failed to build spatial-correlation-sampler
Installing collected packages: spatial-correlation-sampler
    Running setup.py install for spatial-correlation-sampler ... error
    ERROR: Command errored out with exit status 1:
     command: /home/lj/software/anaconda3/envs/MotionSqueeze/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0z5c3sl4/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/
    Complete output (57 lines):
    /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
      return torch._C._cuda_getDeviceCount() > 0
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-9.0'
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/spatial_correlation_sampler
    copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
    copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py", line 57, in <module>
        launch_setup()
      File "/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py", line 52, in launch_setup
        "Topic :: Scientific/Engineering :: Artificial Intelligence"
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 378, in build_extensions
        self._check_abi()
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 734, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 282, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 242, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'g++-5']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lj/software/anaconda3/envs/MotionSqueeze/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3kl5fqr4/spatial-correlation-sampler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0z5c3sl4/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by XiaoXueHou** [comment]
Here are the environment screenshots:
![image](https://user-images.githubusercontent.com/37476521/115147616-6f6ac300-a08e-11eb-9e94-e4cd8e238bdd.png)

**Comment by XiaoXueHou** [comment]
I have followed your instruction about another method on README: python setup.py install. Unfortunately, It seems to meet problem too. The only fortunate thing is fewer error information than using pip. Could you please help me with it QAQ....
Here is the Error information:
(MotionSqueeze) lj@1080ti:~/Pytorch-Correlation-extension$ python setup.py install
running install
running bdist_egg
running egg_info
creating Correlation_Module/spatial_correlation_sampler.egg-info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/spatial_correlation_sampler
copying Correlation_Module/spatial_correlation_sampler/__init__.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
copying Correlation_Module/spatial_correlation_sampler/spatial_correlation_sampler.py -> build/lib.linux-x86_64-3.6/spatial_correlation_sampler
running build_ext
building 'spatial_correlation_sampler_backend' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/Correlation_Module
gcc -pthread -B /home/lj/software/anaconda3/envs/MotionSqueeze/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include -I/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/TH -I/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/lj/software/anaconda3/envs/MotionSqueeze/include/python3.6m -c Correlation_Module/correlation.cpp -o build/temp.linux-x86_64-3.6/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:9:0,
                 from /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/torch/extension.h:4,
                 from Correlation_Module/correlation.cpp:1:
Correlation_Module/correlation.cpp: In lambda function:
Correlation_Module/correlation.cpp:102:56: **error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘c10::ScalarType’
           AT_DISPATCH_FLOATING_TYPES(input1.scalar_type(), "correlation_forward_cpp", ([&] {
                                                        ^
/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro ‘AT_DISPATCH_FLOATING_TYPES’
     const at::Type& the_type = TYPE;                                         \
                                ^
Correlation_Module/correlation.cpp: In lambda function:
Correlation_Module/correlation.cpp:150:52: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘c10::ScalarType’
       AT_DISPATCH_FLOATING_TYPES(input1.scalar_type(), "correlation_backward_cpp", ([&] {
                                                    ^
/home/lj/software/anaconda3/envs/MotionSqueeze/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro ‘AT_DISPATCH_FLOATING_TYPES’
     const at::Type& the_type = TYPE;                                         \
                                ^
error: command 'gcc' failed with exit status 1**

**Comment by InnovArul** [comment]
try `pip install git+https://github.com/ClementPinard/Pytorch-Correlation-extension`?

**Comment by XiaoXueHou** [comment]
Hi ! I have just tried "try pip install git+", but It didn't seem to work.....(Ｔ＿Ｔ). Here are the full error information. Could you help me again🙏😢🤕
![image](https://user-images.githubusercontent.com/37476521/115169146-cbb1ff00-a0ef-11eb-9161-070129e2f716.png)
![image](https://user-images.githubusercontent.com/37476521/115169188-e5ebdd00-a0ef-11eb-8d7d-42729e424a69.png)
![image](https://user-images.githubusercontent.com/37476521/115169230-03b94200-a0f0-11eb-8007-53c71f85e8d2.png)
![image](https://user-images.githubusercontent.com/37476521/115169246-13d12180-a0f0-11eb-8f7f-71db7e701d71.png)
![image](https://user-images.githubusercontent.com/37476521/115169266-2186a700-a0f0-11eb-8fc7-273c858b8e33.png)

**Comment by XiaoXueHou** [comment]
Here is my environment information:
![image](https://user-images.githubusercontent.com/37476521/115188612-c1a3f680-a117-11eb-88cb-f0b30e10aefb.png)

**Comment by ClementPinard** [comment]
Hi, what is your pytorch version ?

**Comment by XiaoXueHou** [comment]
@ClementPinard Hi ! 
Actually, I find be able to install it successfully in Cuda 10.1 with Pytorch==1.6 using "pip install git+https://github.com/ClementPinard/Pytorch-Correlation-extension".

I am wanderding if I could make it【spatial-correlation-sampler==0.1.0】 in Cuda9.0 with Pytorch=1.0.1？
Because I'd like to reproduce a work in [ECCV2020](https://github.com/arunos728/MotionSqueeze/blob/master/conda_list.txt), and it installed "spatial-correlation-sampler==0.1.0" in my environment。

I have tried to use both two methods【pip install git + & python setup.py install 】 to install it, but  neither worked. 

The first pic is my environment and the sec is Error info.
![image](https://user-images.githubusercontent.com/37476521/115326331-b4424700-a1bf-11eb-9da0-eb15574c9e31.png)
![image](https://user-images.githubusercontent.com/37476521/115326872-8f020880-a1c0-11eb-98d3-2cac292f6b4c.png)

The full error information I have attached it in _Error_1.doc_ when I used "pip install spatial-correlation-sampler==0.1.0" . 【But it is toooooooooooo much (T_T)】🙏

It will update Pytorch to 1.8.1 if I use "pip install spatial-correlation-sampler" directly. What's more the full Error information has been attached in _Error_2.doc_ 【A bit fewer than the first one】

The installation in CUDA9.0 is really a dreadful challenge for me. Sincerely hope to get your help！

[Error_2.txt](https://github.com/ClementPinard/Pytorch-Correlation-extension/files/6340336/Error_2.txt)
[Error_1.txt](https://github.com/ClementPinard/Pytorch-Correlation-extension/files/6340337/Error_1.txt)

**Comment by ClementPinard** [comment]
Cool, did not know it was used in a published work !

Does the code work with a more up to date config ? The front Api for pytorch has not changed too much since 1.0.1

Other than that you can try to install previous versions by Chery picking previous tags in the git.

**Comment by XiaoXueHou** [comment]
@ClementPinard Nope! The source code need to be run with Pytorch<=1.3.0 for some reason ( Beause the compution for backward or so on...), I have tried to installed "spatial-correlation-sampler == 0.3.0" successfully in CUDA 10.1 with Pytorch==1.6, but it indicated some Error happened during traing for a high version Pytorch.  And what do you mean "Chery"?

**Comment by XiaoXueHou** [comment]
@ClementPinard  OMG.... I have installed all the required Libs described in the [ECCVwork ](https://github.com/arunos728/MotionSqueeze/blob/master/conda_list.txt) and tried N times , but it still failed to install "spatial-correlation-sampler==0.1.0"(T_T)（T_T)（T_T). Could you tell me if the Module can be installed in CUDA 9.0 with GCC5.4.0 and Pytorch1.0.1 from your Knowledge please🙏 Looking forward to your reply sincerely~
