### ISSUE TITLE
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory.

### ISSUE THREAD

**Issue by houhouhouhou11** [ClementPinard/Pytorch-Correlation-extension#73]
Hello:
  thanks for your sharing. I can use torch-cuda_101.1 normally. 
  But when I import the spatial_correlation_sampler, ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory.
   Ps: I updated the cuda from 9.2 to 10.1.
Thank you very much！

**Comment by ClementPinard** [comment]
Hi, the way I see it, you just need to rebuild from scratch so that it will link against cuda 10 instead of cuda9. Remove and reinstall from pip or do `python setup.py clean` and `python setup.py install` if you built from source.

Clément
