### ISSUE TITLE
Correlation is zero in Multi-GPU environment

### ISSUE THREAD

**Issue by KangBK0120** [ClementPinard/Pytorch-Correlation-extension#78]
Hi, first of all, thanks for sharing this module.

the correlation value is always zero in the muti-GPU environment when the inputs are not in the first GPU.  

![image](https://user-images.githubusercontent.com/25279765/130199940-2102be0c-ae6d-4061-877f-5d78e6a6e40d.png)

totally works fine as expected.

However, if I try to use other GPUs, it returns 0 correlation.

![image](https://user-images.githubusercontent.com/25279765/130200021-e2a7e695-60da-49c8-9eea-ce270104cf13.png)

And by using CUDA_VISIBLE_DEVICES" to point a single GPU, this problem is gone.

![image](https://user-images.githubusercontent.com/25279765/130200313-dd40fddd-220b-4aca-92b8-bb28c3f2fd7a.png)

**Comment by KangBK0120** [comment]
I'm using torch 1.9.0 and 3090 RTX with cuda version 11.1

**Comment by ClementPinard** [comment]
Hi, did you try to install it from source ? There was a discussion about this problem a while back and was solved by @InnovArul  #59
