### ISSUE TITLE
Segmentation Fault when running on a cluster

### ISSUE THREAD

**Issue by tangshixiang** [ClementPinard/Pytorch-Correlation-extension#8]
I got the segmentation fault when I submit my code to a cluster, but It is fine when I ran it on my personal computer. SO HOW TO FIX IT?

**Comment by ClementPinard** [comment]
What is your hardware like in your cluster ? What is your CUDA version, and your pytorch version ? Do you compile it on the cluster ?

**Comment by tangshixiang** [comment]
CUDA version: 9.0.176
Pytorch version 0.4.1
When I compile it on the cluster, It is fine. Only when I ran the module, SEGMENTATION FAULT pops out.

**Comment by ClementPinard** [comment]
Closing this one as it is probably related to #6
