### ISSUE TITLE
parameter setting problem

### ISSUE THREAD

**Issue by z-fy-31** [ClementPinard/Pytorch-Correlation-extension#81]
I used the correlation_package used in Flownet2 of NVIDIA and the parameters are

> self.corr  = Correlation(pad_size=4, kernel_size=1, max_displacement=4, stride1=1, stride2=1, corr_multiply=1)

and now I use spatial-correlation-sampler with the parameters:

> out_corr = spatial_correlation_sample(input1, input2, kernel_size=1, patch_size=9, stride=1, padding=0, dilation_patch=1)

However, I got different results with these correlation-packages. What's wrong? Thanks.

**Comment by ClementPinard** [comment]
Can you post a replication script and an output sample as well ? I agree with you that your parameter seem good and should produce the same result, as long as the inputs are the same.
