### ISSUE TITLE
Get slower after using correlation extension

### ISSUE THREAD

**Issue by RongchangLi** [ClementPinard/Pytorch-Correlation-extension#86]
Hello, I find it get slower after using SpatialCorrelationSampler (from 0.647 to 0.832 to run a iteration). Do you know then possible problems? Maybe it is the cuda(11.4) or cudnn(8.2.4) problem?

**Comment by ZhaoChongren** [comment]
How did you install this installation package in CUDA11.4. I have never been able to install
