### ISSUE TITLE
failed to python setup.py install

### ISSUE THREAD

**Issue by ChuLinTang** [ClementPinard/Pytorch-Correlation-extension#89]
hi, there are something went wrong and i can't figure it out.

python setup.py install
running install
running bdist_egg
running egg_info
writing Correlation_Module/spatial_correlation_sampler.egg-info/PKG-INFO
writing dependency_links to Correlation_Module/spatial_correlation_sampler.egg-info/dependency_links.txt
writing requirements to Correlation_Module/spatial_correlation_sampler.egg-info/requires.txt
writing top-level names to Correlation_Module/spatial_correlation_sampler.egg-info/top_level.txt
reading manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'Correlation_Module/spatial_correlation_sampler.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'spatial_correlation_sampler_backend' extension
gcc -pthread -B /home/gx115/SoftWares/anaconda3/envs/MS/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DUSE_CUDA -I/home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include -I/home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/TH -I/home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/gx115/SoftWares/anaconda3/envs/MS/include/python3.6m -c Correlation_Module/correlation.cpp -o build/temp.linux-x86_64-3.6/Correlation_Module/correlation.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=spatial_correlation_sampler_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:9:0,
                 from /home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/torch/extension.h:4,
                 from Correlation_Module/correlation.cpp:1:
Correlation_Module/correlation.cpp: In lambda function:
Correlation_Module/correlation.cpp:102:56: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘c10::ScalarType’
           AT_DISPATCH_FLOATING_TYPES(input1.scalar_type(), "correlation_forward_cpp", ([&] {
                                      ~~~~~~~~~~~~~~~~~~^~
/home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro ‘AT_DISPATCH_FLOATING_TYPES’
     const at::Type& the_type = TYPE;                                         \
                                ^~~~
Correlation_Module/correlation.cpp: In lambda function:
Correlation_Module/correlation.cpp:150:52: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘c10::ScalarType’
       AT_DISPATCH_FLOATING_TYPES(input1.scalar_type(), "correlation_backward_cpp", ([&] {
                                  ~~~~~~~~~~~~~~~~~~^~
/home/gx115/SoftWares/anaconda3/envs/MS/lib/python3.6/site-packages/torch/lib/include/ATen/Dispatch.h:15:32: note: in definition of macro ‘AT_DISPATCH_FLOATING_TYPES’
     const at::Type& the_type = TYPE;                                         \
                                ^~~~
error: command 'gcc' failed with exit status 1

**Comment by ClementPinard** [comment]
Hi sorry for the late answer.

Are you still experiencing the problem ? What pytorch version were you using at the time ?
