### ISSUE TITLE
Output are all zero

### ISSUE THREAD

**Issue by ltkong218** [ClementPinard/Pytorch-Correlation-extension#9]
I have used this correlate module, but the output tensor are all zero. I don't know why. My input tensors are all 'torch.cuda.FloatTensor'.
When I use cpu version, the output have non zero values, but when it converts to cuda version, the output value are all zero.

**Comment by ClementPinard** [comment]
Hello, is this problem still happening ? Can you specify your gcc and cuda versions ?

**Comment by ltkong218** [comment]
Yes, it still happens. My gcc version 5.4.0, cuda version 9.0, pytorch version 0.4.1.

**Comment by ltkong218** [comment]
[correlation_test.txt](https://github.com/ClementPinard/Pytorch-Correlation-extension/files/2670772/correlation_test.txt)

**Comment by ClementPinard** [comment]
Is this problem still ocurring ? Unfortunately I have not experienced this problem in all my tests.
There has been several updates since this issue so maybe things have changed.

**Comment by ltkong218** [comment]
I think it is okay now. I am using an older version of correlation module in PyTorch 0.4.0 and verify both results are the same. The problem might be the compatibility of spatial_correlation_sample module. Thanks!

**Comment by ClementPinard** [comment]
Great then !
feel free to reopen the issue if you encounter problems with latest version
